astronomer/airflow-chart

README.md

Currently command shows w/ horizontal scrollbar

Edit command to be multiline

---

.circleci/config.yml
CONTRIBUTING.md
Chart.yaml
README.md
bin/clean-slate
bin/install-ci-tools
bin/lint
bin/package
bin/reset-local-dev
bin/run-ci
bin/start-kind-cluster
templates/statsd/statsd-deployment.yaml
values.yaml

... and also patch for compatibility with up to k8s version 1.17
After merging, enable circle CI for this repo

Make a CI testing process

---

templates/secrets/metadata-connection-secret.yaml
templates/secrets/result-backend-connection-secret.yaml
values.yaml

For using conn string in KEDA we need to identify the sslmode

Identify ssl mode in conn string

---

.circleci/config.yml

Use Python 3.7 in CI

---

.circleci/config.yml

Fix installation path of CI tool

---

.circleci/config.yml
bin/release

The error was
```
pyenv: python2: command not found
The `python2' command exists in these Python versions:
2.7.12
```
~~I did not test this will fix it. I'm not sure how to do so...~~

Fix python version error

---

.circleci/config.yml
bin/release

Fix python version error in CI

---

.circleci/config.yml
bin/release

Fix gcloud configuration in CI

---

.circleci/config.yml
bin/release

Fix helm index build to include airflow

---

.circleci/config.yml
bin/release

Fix path to helm index

---

bin/run-ci
templates/NOTES.txt
templates/_helpers.yaml
templates/configmap.yaml
templates/ingress.yaml
templates/webserver/webserver-deployment.yaml

fix https://github.com/astronomer/issues/issues/459

Add support of path based airflow ingress

---

Chart.yaml
README.md
templates/workers/worker-kedaautoscaler.yaml

Fix to match new naming convention for KEDA 1.2

---

README.md
templates/workers/worker-kedaautoscaler.yaml

Changes for compliance with keda 1.2

---

bin/start-kind-cluster

Minor cleanup of airflow chart CI script
**Checklist**
n/a

Small cleanup of CI script

---

Chart.yaml

Bump to 0.12.0-alpha.1

---

templates/workers/worker-kedaautoscaler.yaml

Fix indent

---

Chart.yaml

Bump 0.12.2-alpha.2

---

README.md

Add link to KEDA project

---

Chart.yaml
templates/secrets/metadata-connection-secret.yaml

Fix where pgbouncer URLs were not available cross-namespace

---

templates/ingress.yaml

fix https://github.com/astronomer/issues/issues/835

fix 404 of flower

---

Chart.yaml
templates/scheduler/scheduler-deployment.yaml
templates/webserver/webserver-deployment.yaml
templates/workers/worker-deployment.yaml
values.yaml

helm template . | grep -A6 annotation
(irrelevant data omitted)
```
--
annotations:
checksum/metadata-secret: 0fae8502ad51064afe5baff2addd57d2ce3c903619878ebb64bb205e31554a59
checksum/result-backend-secret: 6b42f18009b6df7e5c2606d12038ff1e89305f7aca5cf0f4e3a85948d9345684
checksum/pgbouncer-config-secret: ed289c0e3972684b92f136223f92ed6b71ed333efaa7953da8465316bacc3575
checksum/airflow-config: 061f7b24707744e6681b4e9150aa69a66aace0dad6d880916cc9e6079e242e2d
cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
--
annotations:
checksum/metadata-secret: 0fae8502ad51064afe5baff2addd57d2ce3c903619878ebb64bb205e31554a59
checksum/pgbouncer-config-secret: ed289c0e3972684b92f136223f92ed6b71ed333efaa7953da8465316bacc3575
checksum/airflow-config: …
```

Configurable Airflow pod annotations

---

Chart.yaml
templates/scheduler/scheduler-deployment.yaml
templates/webserver/webserver-deployment.yaml
templates/workers/worker-deployment.yaml
values.yaml

* Configurable Airflow pod annotations
* Increment version

Configurable Airflow pod annotations (#49)

---

Chart.yaml
templates/ingress.yaml

Refactor Flower Ingress (#50)

---

bin/release

same idea as https://github.com/astronomer/astronomer/pull/584

Reduce cache time for index file

---

templates/ingress.yaml

fix https://github.com/astronomer/issues/issues/957

Add redirect old style uri to new style for airflow api too

---

README.md

`console` is used wrongly in the repo

Change Syntax Highlighting for code-blocks

---

.circleci/config.yml
bin/reset-local-dev
bin/run-ci
bin/start-kind-cluster
templates/redis/redis-statefulset.yaml

Closes: https://github.com/astronomer/issues/issues/978
If CI passes, that indicates these three executors work on Kubernetes 1.14-1.17

Test Local, Kubernetes, and Celery executors in CI

---

templates/webserver/webserver-deployment.yaml

issue when 'astro deploy' new airflow version: webserver does not start

Wait for DB migration with the right image

---

templates/scheduler/scheduler-serviceaccount.yaml
templates/webserver/webserver-deployment.yaml
templates/webserver/webserver-serviceaccount.yaml
templates/workers/worker-kedaautoscaler.yaml
templates/workers/worker-serviceaccount.yaml
values.yaml

fix https://github.com/astronomer/issues/issues/851

allow service account annotations

---

.circleci/config.yml

Use new matrix builds Circle CI feature

---

.circleci/config.yml
templates/scheduler/scheduler-deployment.yaml
values.yaml

Closes: https://github.com/astronomer/issues/issues/1560

Fix HA-ready scheduler probes

---

templates/create-user-job.yaml

Based on https://github.com/apache/airflow/pull/10291

Run create-user-job as user with specified id

---

bin/run-ci
templates/create-user-job.yaml
templates/run-airflow-migrations.yaml
templates/scheduler/scheduler-deployment.yaml
tests/run-airflow-migrations-job_test.yaml
tests/scheduler_scheduler-deployment_test.yaml
values.yaml

create separate job to run airflow migrations

---

files/pod-template-file.yaml
templates/configmap.yaml
templates/run-airflow-migrations.yaml

Add logging volume to pod_template_file

---

.circleci/config.yml
.pre-commit-config.yaml
bin/clean-slate
bin/package
bin/release
bin/reset-local-dev
bin/run-ci
bin/start-kind-cluster

Reduce the complexity of the helm release process by using a new docker image I've created for doing that task. Also clean up a bunch of shell script code, fix shellcheck complaints, and add pre-commit config.
These are CI changes only, so there's no risks for our customers, just the potential for CI to misbehave.

Reduce CI job complexity. Use quay.io/astronomer/ci-helm-release

---

templates/run-airflow-migrations.yaml

Checking for presence of values before populating the template for affinities, tolerations and node selectors
tested manually with helm template

Conditional checking around node selectors, tolerations and affinity

---

.circleci/config.yml
requirements.lock

The old helm repository is being deprecated. This change set replaces references to the old one with references to the new one.

Update repository to non-deprecated one

---

files/pod-template-file.yaml
tests/pod-template-file_test.yaml

Cherry picks for pod template file

---

Chart.yaml

Merge this _after_ #159.
Once this is done, we can then to a fast-forward merge of the `release-0.18` branch to include this merged commit.

Bump version to 0.18.2

---

.circleci/config.yml

Deprecate kube 1.14, 1.15. Add kube 1.19.
Rleated to astronomer/issues#2266

Remove k8s 1.15, 1.14. Add 1.19.

---

README.md
templates/webserver/webserver-deployment.yaml
tests/webserver_webserver-deployment_test.yaml
values.yaml

Prevent Airflow Webserver Reboot for Airflow 2.0+
Resolves https://github.com/astronomer/issues/issues/2123

Prevent Airflow Webserver Reboot for Airflow 2.0+

---

templates/_helpers.yaml
templates/flower/flower-deployment.yaml
values.yaml

Resolves astronomer/issues#2368

Remove redundant flower_image

---

templates/_helpers.yaml
values.yaml

we are looking to be able to add more settings to the pgbouncer config file.  this is a less targeted, more open, approach to allowing a user to add configuration to a few places in the pgbouncer configuration file.
i wanted to open this up to get the conversation going early about this approach and just get any feedback people had.  i will be adding tests here in a bit.
let me know your thoughts!

add ability to add more settings to pgbouncer config secret

---

tests/secrets_elasticsearch-secret_test.yaml

Fix spelling

---

templates/_helpers.yaml
values.yaml

cherry picked commit to master into release 0.18 branch.  bumped version to `0.18.7` release.

add ability to add more settings to pgbouncer config secret (#184)

---

README.md

I missed it in #208 but I think it listing them together would be better :)

Re-organize Updating DAGs section in README

---

Chart.yaml

https://www.astronomer.io/static/airflowNewA.png does not exist

Fix broken Airflow icona

---

.circleci/config.yml

- Use contex: github-repo
- Use context: gcp-astronomer-prod
- Improve regex
- Rename step

Use CircleCI contexts

---

bin/example_project/dags/example_dag.py
bin/install-ci-tools
bin/run-ci
tests/functional-tests/test_chart.py

Currently we don't a test where we run a DAG and a task. This will give us better coverage and prevent chart errors.

Add test to run an example DAG

---

templates/flower/flower-auth-sidecar-configmap.yaml
templates/ingress.yaml
templates/webserver/webserver-auth-sidecar-configmap.yaml
templates/webserver/webserver-service.yaml
values.yaml

CI on (#221) passed, however pre-commits failed when they were merged to master. This commit fixes it

Fix failing pre-commit

---

requirements.lock
requirements.yaml

bump chart version

---

README.md

I noticed a few leftovers/mistakes in the README.

Minor cleanup of README.md

---

templates/_helpers.yaml
templates/airflow-scc-anyuid.yaml
tests/scc_test.yaml

Resolves astronomer/issues#3597

add service accounts for all airflow deployment components

---

Chart.yaml

Bump airlfow version to 1.3.0 and release to 1.0.6

bump airflow to 1.3.0

---

values.yaml

update pgbouncer and pgbouncer exporter base image 
bump pgbouncer image
Resolves astronomer/issues#3963
> Please add helm unit testing, if applicable. The docs are regretfully sparse for helm unit testing, [here](https://github.com/astronomer/helm-unittest/blob/main/DOCUMENT.md) is what we have to work with. In general, these kind of tests can be used for specific assertions like 'when these values are set, the resource ends up looking like XYZ' but not for generalized assertions like 'for all resources, make sure the namespace is not set to the release name'.
> Please also add to the system testing [here](../tests/functional-tests). This kind of testing allows you to connect into …

bump pgbouncer image

---

CODEOWNERS

Unfortunately I won't have time to review PRs on this repo anymore

Removing myself as CodeOwner

---

values.yaml

* bump ap-pgbouncer 1.17.0 -> 1.17.0-1
* bump ap-pgbouncer-exporter 0.13.0-1 -> 0.13.0-2
NA

update vendor images

---

Chart.yaml
values.yaml

update astronomer airflow chart version 1.4.0 -> 1.4.1
NA
NA

update astronomer airflow chart version

---

.circleci/config.yml
bin/package-and-release-internal

update ci-helm-release image to ci-helm-release:2022-04
NA
NA

update ci helm release image

---

.circleci/config.yml
bin/package-and-release-internal

* update ci helm release image
* no more helm3 tag is required  , moved to helm by default
NA
NA

update ci helm release image (#310)

---

.circleci/config.yml
Makefile
bin/run-ci
tests/chart_tests/conftest.py
tests/chart_tests/requirements.in
tests/chart_tests/requirements.txt
tests/chart_tests/test_docker_images.py
tests/functional-tests/requirements.txt

Adding the docker image pull test. This test ensures that the all declared docker images are pullable.
https://github.com/astronomer/issues/issues/3968
This change is about to add the test case.

Adding Docker Image Pull Test

---

.github/pull_request_template.md

Add a section to the PR template detailing which branches the change should be merged / cherry-picked into.
N/A
None needed.
This change isn't needed in any release branches because GH uses the default branch's pull request template.

Add section: Merging

---

values.yaml

* update statsd-exporter 0.18.0 -> 0.22.4
* update pgbouncer 1.17.0-1 -> 1.17.0-2
* update pgbouncer-exporter 0.13.0-2 -> 0.13.0-3
NA
cherry-picked to all release branches

update vendor packages

---

Chart.yaml
values.yaml

security fixes for pgbouncer, pgbouncer exporter 
enhancements for git-sync service , statsd exporter
NA

Add security fixes to release 1.5 branch

---

templates/logging-sidecar-configmap.yaml

* this creates usable new fields from json message for elasticsearch documents, which can be further used to query documents
* remove unneeded fields like host and file while ingesting data to elasticsearch
Do not merge this PR until this text is replaced with links to related issues.
while data gets ingested from vector sidecar to elasticsearch - users can see all the field  data  elasticsearch , that can be used to run queries 

update vector config

---

templates/logging-sidecar-configmap.yaml

NOVA-9650 handle changes to airflow 2.3.0 log's "log_id" field

log_id logs mapping in Vector

---

values.yaml

Elasticsearch_log_id value based on airflow version

Ternary operator Elasticsearch_log_id

---

Chart.lock
Chart.yaml

released 1.7.0-astro with rishabs updated changes that were merged to OSS
https://github.com/apache/airflow/pull/25031
release-1.7

bump chart to use 1.7.0-astro

---

Chart.yaml

bump chart version to 1.7.0-rc4
just updating version
1.7.0

bump chart version to 1.7.0-rc4

---

Chart.yaml

bump to rc 1.7.0

---

Chart.yaml
bin/package-and-release-internal

update chart version 1.4.2 -> 1.4.3
NA
NA
applies to release-1.4

chart version 1.4.3

---

Chart.lock
Chart.yaml

bump chart
QA
master/release1.7

bump version of chart 1.7.0

---

templates/git-sync-relay/git-sync-relay-deployment.yaml
tests/chart_tests/test_git_sync_relay_deployment.py

ssh-secret not required when sshPrivateKeySecretName not provided (houston only sends sshPrivateKeySecretName when sshKey config set )
- https://github.com/astronomer/issues/issues/4059

add git-secret only if the sshPrivateKeySecretName provided

---

Chart.yaml

- airflow-chart version 1.7.1
NA
NA
Merge to release-1.7 only **after 0.31.0 and 0.30.3 are released**.

chart version 1.7.1

---

Chart.yaml

* 1.7.1 -> 1.7.2
NA - This is an new patch version release to include gitsync relay features
NA
merge to release-1.7 branch.

version 1.7.2

---

values.yaml

hotfix flower-ui to work around an airflow bug
- Described in https://github.com/astronomer/issues/issues/5252
- Supercedes https://github.com/astronomer/astronomer/pull/1753
- Upstream issue we are working around https://github.com/apache/airflow/issues/27402
We should test that flower-ui comes up without issues.
Merge into release-1.7.

hotfix flower ui

---

templates/git-sync-relay/git-sync-relay-deployment.yaml
tests/chart_tests/__init__.py
tests/chart_tests/test_git_sync_relay_deployment.py
values.yaml

Allows configurable  resources and security to optimise git sync service
https://github.com/astronomer/issues/issues/5355
added static test cases to validate resource (requests and limits) and security context
cherry-pick to 1.7 release.

allow resource and securitycontext overrides for git-sync service

---

.circleci/config.yml
.circleci/generate_circleci_config.py
bin/start-kind-cluster

K8s 1.25 support for airflow-chart
https://github.com/astronomer/issues/issues/4481

K8s 1.25 upgrade

---

.circleci/config.yml
.circleci/generate_circleci_config.py
tests/__init__.py

K8s 1.26 support for airflow-chart
https://github.com/astronomer/issues/issues/5366

add k8s 1.26 support to airflow-chart

---

README.md
UPDATING.md

- Clarify some versioning details.
- Detail removal of HPA.
This is somewhat related to:
- https://github.com/astronomer/issues/issues/5373
- https://github.com/astronomer/issues/issues/4481
N/A, these are just docs changes.
The README.md changes could go to all branches, but the UPDATING.md changes should only go to release-1.8 and newer.

Clarify some versioning details. Detail removal of HPA.

---

.pre-commit-config.yaml

* resolves pip-shims dependency issue
https://github.com/astronomer/issues/issues/5382
pre-commit pipeline will pass without any issues 
merge to all valid releases.

update isort pre-commit revision

---

Chart.yaml

update chart version 1.7.6
NA
NA
merge directly to release 1.7 branch

update chart version to 1.7.6

---

templates/git-sync-relay/git-sync-relay-deployment.yaml
templates/logging-sidecar-configmap.yaml
values.yaml

Do not merge this PR until this description is replaced with relevant info.
vector ingested logs in astro-ui
https://github.com/astronomer/issues/issues/5246

Airflow chart/add gitsync sidecar container support

---

.circleci/config.yml
.circleci/config.yml.j2
.circleci/generate_circleci_config.py
CONTRIBUTING.md
README.md
tests/__init__.py
tests/chart_tests/helm_template_generator.py

Remove K8s 1.21 support from astronomer/astronomer
https://github.com/astronomer/issues/issues/5452

remove 1.21 k8s supported version

---

templates/git-sync-relay/git-sync-relay-deployment.yaml
tests/chart_tests/test_git_sync_relay_deployment.py
values.yaml

Adding Custom Git Sync Relay Docker Image for git-sync-relay.
https://github.com/astronomer/issues/issues/5539

Updating git-sync-relay docker image

---

.circleci/config.yml
.circleci/generate_circleci_config.py
.pre-commit-config.yaml
CONTRIBUTING.md
bin/install-ci-tools
bin/start-kind-cluster
tests/chart_tests/requirements.txt
tests/functional-tests/requirements.txt

Bump dev component versions. This PR was created in response to dependabot PRs.
- https://github.com/astronomer/airflow-chart/pull/432
- https://github.com/astronomer/airflow-chart/pull/433
These are all test changes, so if tests pass we're good.

Update dev component versions

---

Chart.yaml

airflow-chart 1.8.6
N/A
All testing has been completed.
Merge only to release-1.8 branch.

version 1.8.6

---

Chart.yaml

updates airflow chart version includes worker fixes
https://github.com/astronomer/issues/issues/5742
QA should able to validate worker pod should work as usual without any probe failures
NA

update airflow chart version 1.9.2

---

Chart.yaml

Add custom chart that includes cron splay changes 
https://github.com/astronomer/issues/issues/5670
QA should able to validate custom cron splay
cherry-pick to release-1.7

update airflow chart version 1.7.1

---

Chart.yaml

update airflow chart version 1.9.4 -> 1.9.5
NA
NA
cherry-pick to release-1.9

update airflow chart version 1.9.5

---

values.yaml

* update vendor packages to airflow chart
* update vector patch image
https://github.com/astronomer/issues/issues/5870
https://github.com/astronomer/issues/issues/5988
https://github.com/astronomer/issues/issues/5947
QA should able to install airflow chart 
cherry-pick to release-1.8

update vendor packages to airflow chart (#468)

---

Chart.yaml

update airflow chart version 1.8.9
NA
NA
cherry-pick to release-1.8

update airflow chart version 1.8.9

---

.circleci/config.yml
.circleci/config.yml.j2
.circleci/generate_circleci_config.py
templates/dag-server/dag-server-service.yaml
templates/dag-server/dag-server-serviceaccount.yaml
templates/dag-server/dag-server-statefulset.yaml
templates/ingress.yaml
tests/chart_tests/test_dag_server_serviceaccount.py
tests/chart_tests/test_dag_server_statefulset.py
tests/chart_tests/test_dag_server_sts.py
tests/chart_tests/test_ingress.py
values.yaml

- Merge @pgvishnuram's changes from https://github.com/astronomer/airflow-chart/tree/add-dagdeployer-support
- Add tests for Vishnu's changes
- Improve ingress tests
- Bump some CircleCI component versions
- Remove deprecated docker remote versions key

Merge vishnu's changes

---

values.yaml

update dag-deploy 0.3.0 -> 0.3.2
https://github.com/astronomer/issues/issues/5969
QA can refer above ticket

update dagserver image 0.3.0 -> 0.3.2

---

Chart.yaml

update airflow chart version 2.0 
https://github.com/astronomer/issues/issues/5969
NA
cherry-pick to release-2.0 branch

update airflow chart version 2.0.0

---

Chart.yaml

update airflow chart version 1.10.0
https://github.com/astronomer/issues/issues/5969
NA
NA

update airflow chart version 1.10.0

---

Chart.yaml

update airflow chart version 1.11.0
https://github.com/astronomer/issues/issues/6423
NA

version 1.11.0

---

Chart.yaml

update astro managed chart version 1.11.1
https://github.com/astronomer/issues/issues/6423
https://github.com/astronomer/issues/issues/6383
NA

update astro managed chart version 1.11.1

---

Chart.yaml

update astronomer airflow chart version 1.11.3
https://github.com/astronomer/issues/issues/6459
https://github.com/astronomer/issues/issues/6436
refer linked issues
cherry-pick to release-1.11.x

update astronomer airflow chart version 1.11.3

---

values.yaml

update dag server version 0.5.0
https://github.com/astronomer/issues/issues/6487
https://github.com/astronomer/issues/issues/6506
check issue ticket

update dag server version 0.5.0

---

Chart.yaml

update airflow chart version 1.11.4
NA
NA
NA

update airflow chart version 1.11.4

---

Chart.yaml

update astronomer airflow chart 1.11.5
NA
NA
NA

update astronomer airflow chart 1.11.5

---

values.yaml

Image Name |  Old-tag|  New-tag 
-- | -- | -- 
ap-statsd | 0.26.1 | 0.27.1
https://github.com/astronomer/issues/issues/6557
QA should validate all the status indicators and scheduler heartbeat

ap-statsd 0.27.1

---

Chart.yaml

update astronomer airflow chart version 1.11.7
https://github.com/astronomer/issues/issues/6620
General QA testing

update astronomer airflow chart version 1.11.7

---

Chart.yaml

update airflow chart version 1.13.2
https://github.com/astronomer/issues/issues/6650
https://github.com/astronomer/issues/issues/6593
https://github.com/astronomer/issues/issues/6594
NA
NA

update airflow chart version 1.13.2

---

templates/dag-deploy/dag-server-auth-sidecar-configmap.yaml
templates/flower/flower-auth-sidecar-configmap.yaml
templates/webserver/webserver-auth-sidecar-configmap.yaml
tests/chart/test_data/dag-server-authsidecar-nginx.conf

This PR fixes an issue where on baremetal installation worker process causing an OOM.
what is worker process ?
worker process that handles the incoming request
setting auto automatically adjust the number of Nginx worker processes based on available cores
what is worker connections ?
maximum number of simultaneous connections that can be opened by a worker process.
- https://github.com/astronomer/issues/issues/6685
QA should validate the values in nginx config when auth sidecar is enabled
cherry-pick to all valid releases

update nginx worker connections and nginx worker process

---

Chart.yaml

update chart version 1.13.4
version update to 1.13.4
NA
NA

update chart version 1.13.4

---

CODEOWNERS

Switch CODEOWNERS from maintainers-astronomer to astronomer-software
NA, KTLO dev type work
NA
Merge everywhere

Switch from maintainers-astronomer to astronomer-software

---

templates/git-sync-relay/git-sync-relay-configmap.yaml
templates/git-sync-relay/git-sync-relay-deployment.yaml
templates/git-sync-relay/git-sync-relay-ingress.yaml
templates/git-sync-relay/git-sync-relay-networkpolicy.yaml
templates/git-sync-relay/git-sync-relay-service.yaml
tests/chart/__init__.py
tests/chart/test_git_sync_relay_deployment.py
tests/chart/test_git_sync_relay_networkpolicy.py
tests/chart/test_git_sync_relay_service.py
tests/chart/test_git_sync_relay_serviceaccount.py
values.yaml

Add support for git-sync webhook feature.
https://github.com/astronomer/issues/issues/6786
This is a new feature so we will need to fully test the aspects of it that are included in 0.37.0.
Merge only to 0.37.0

6786 gitsync webhook

---

Chart.yaml

Version 1.13.6
N/A, regular KTLO 0.37.0 work.
This is just a version bump, no testing is needed for this PR.
Only merge into release-1.13 branch.

airflow-chart version 1.13.6

---

Chart.yaml

update airflow chart version 1.14.0
NA, ktlo work
No testing required 
cherry-pick to master and create new release brancg 1.14

update airflow chart version 1.14.0

---

tests/chart/test_pod_template.py
values.yaml

revert add workers resource spec to pod template
revert PR https://github.com/astronomer/airflow-chart/pull/557
related issue - https://github.com/astronomer/issues/issues/6926
No testing required 
merge to release-1.13

revert add workers resource spec to pod template

---

templates/_helpers.yaml
tests/chart/test_dag_server_statefulset.py
values.yaml

Add logging sidecar resource spec support for dag server and git sync server
- https://github.com/astronomer/issues/issues/7153
helm unit tests included
merge to all branches

support logging sidecar resource support

---

Chart.yaml
tests/chart/test_airflow_scheduler.py
tests/chart/test_dag_processor.py
tests/chart/test_triggerer.py

update airflow chart version
NA, ktlo work
NA
merge to release-1.14

update airflow chart version

---

templates/dag-deploy/dag-deploy-rolebinding.yaml
tests/chart/test_dag_deploy_rolebinding.py

update dag downloader rbac for dag processor 
- Related astronomer/issues#6572
QA should able to verify if dag downloader works as expected with dag processor
merge to master , releaase-1.14

update dag downloader rbac for dag processor 

---

Chart.yaml

update airflow chart version 1.14.3
ktlo work
NA
NA

update airflow chart version 1.14.3

---

Chart.lock
Chart.yaml

This PR intends to release 1.15.1 version of Airflow chart
https://github.com/astronomer/issues/issues/7289
Master

version 1.15.1 

---

Chart.lock
Chart.yaml

This PR description intends to update airflow-chart to 1.15.2
https://github.com/astronomer/issues/issues/7066
Master, 1.15.2

Airflow update to 1.15.2

---

README.md
templates/git-sync-relay/git-sync-relay-ingress.yaml
templates/ingress.yaml

Remove ingress.acme
https://github.com/astronomer/issues/issues/7473
This can be tested with existing flows.
This should only go into 1.15

Remove acme

---

Chart.lock
Chart.yaml
templates/_helpers.yaml
templates/ingress.yaml
tests/chart/test_airflow_scheduler.py
tests/chart/test_dag_processor.py
tests/chart/test_triggerer.py
values.yaml

Enables OSS helm chart 1.17 with airflow3 support
- https://github.com/astronomer/issues/issues/7388
QA should able to create airflow2 and airflow3 based deployments from astronomer platform
merge to master

airflow oss helm chart 1.17.x official release changes

---

Chart.yaml
bin/run-ci
tests/__init__.py
tests/chart/test_docker_images.py
values.yaml

replace bitnami images with astronomer quay
- https://github.com/astronomer/issues/issues/7848
Gettings tests passed should be fine
merge to master and release-1.0

replace bitnami images with astronomer quay

---

.circleci/config.yml
.circleci/config.yml.j2

Remove fix-7872-chart-release branch from circleci
Master only

remove fix-7872-chart-release branch
