- templates/configmap.yaml
This would help us in case we have some networking issues or our index grows massive
> Allow retrying on ES timeouts

- .circleci/config.yml
the GCP_TOKEN auth was accidentally placed in the github release part instead of the helm chart release part.
**Checklist**
n/a
> Move GCP auth to the right spot

- Chart.yaml
- templates/configmap.yaml
- values.yaml
Some users may need to override the Airflow pod mutation hook.
Example of this change at work:
```
e4384cda2b17:  ~/shared/airflow-chart 
_ helm template . -f ./config.yaml | grep -A9 'airflow_local_settings.py:'
airflow_local_settings.py: |
from airflow.contrib.kubernetes.pod import Pod
from airflow.configuration import conf
def pod_mutation_hook(pod: Pod):
pass
---
e4384cda2b17:  ~/shared/airflow-chart 
_ cat config.yaml
scheduler:
airflowLocalSettingsOverride: |
from airflow.contrib.kubernetes.pod import Pod
from airflow.configuration import conf
def pod_mutation_hook(pod: Pod):
pass
e4384cda2b17:  ~/shared/airflow-chart 
_ helm template . | grep -A25 'airflow_local_settings.py:'
airflow_local_settings.py: |
from airflow.contrib.kubernetes.pod import Pod
from airflow.configuration …
```
> Add option to override airflow_local_settings.py

- .circleci/config.yml
- templates/pgbouncer/pgbouncer-deployment.yaml
- templates/pgbouncer/pgbouncer-poddisruptionbudget.yaml
- templates/scheduler/scheduler-poddisruptionbudget.yaml
- values.yaml
This PR makes the PDB on the scheduler and pgbouncer optional and disabled by default. By disabling in our cloud we may be able to avoid needing to do the manual compaction.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node
> Disable the scheduler PodDisruptionBudget

- templates/configmap.yaml
- templates/statsd/statsd-deployment.yaml
- templates/statsd/statsd-networkpolicy.yaml
- templates/statsd/statsd-service.yaml
- values.yaml
- Allows user to enable/disable `statsd`
- `statsd` is not necessary when running this chart on its own
- I left the default `enabled` for now, but may be better to default to `disabled` and override this value with `houston`
- Related to astronomer/issues#822
> Add ability to enable/disable statsd component

- templates/_helpers.yaml
Adds correct templated values from Kubernetes Secrets to AIRFLOW__KUBERNETES_SECRETS environment variables.  Previously was resulting in CreateContainerConfigError on the Task Pods, since the Secrets were not being referenced by the right name (secrets not found).
> Replace Kubernetes Secrets w/ correct value

- templates/workers/worker-horizontalpodautoscaler.yaml
- Indentation is 8 spaces. Should be 4.
- Causes error when this resource is enabled `Error: YAML parse error on airflow/templates/workers/worker-horizontalpodautoscaler.yaml: error converting YAML to JSON: yaml: line 14`
- Related to astronomer/issues#889
> Fix toYaml indent

- templates/ingress.yaml
tl;dr Fix without adding flag
**it works without follow redirect for old links:**
```
curl -X GET 'https://heliocentric-spectrum-1721-airflow.staging.astronomer.io/api/experimental/dags/example_dag/dag_runs' -H 'cookie: astronomer_staging_astronomer_io_auth=token'
{
"dag_id": "example_dag",
"dag_run_url": "/heliocentric-spectrum-1721/airflow/graph?dag_id=example_dag&execution_date=2020-03-17+12%3A21%3A53%2B00%3A00",
"execution_date": "2020-03-17T12:21:53+00:00",
"id": 7,
"run_id": "manual__2020-03-17T12:21:53+00:00",
"start_date": "2020-03-17T12:21:53.828586+00:00",
"state": "running"
},
{
"dag_id": "example_dag",
"dag_run_url": "/heliocentric-spectrum-1721/airflow/graph?dag_id=example_dag&execution_date=2020-03-17+12%3A25%3A01%2B00%3A00",
"execution_date": "2020-03-17T12:25:01+00:00", …
```
> add proxy_pass if old airflow url has api rather than redirect

- templates/scheduler/scheduler-deployment.yaml
Uses the user image to run the migrations, ensuring the correct versions migrations run.
Closes https://github.com/astronomer/issues/issues/1050
> Use users image for migrations

- Chart.yaml
- templates/_helpers.yaml
- values.yaml
A customer reported using these configurations to avoid verbose logging from pgbouncer, which was causing issues for them. I think that connect / disconnect logging is not that helpful in this scenario where there are many components that are constantly connecting and disconnecting, by design. The 'verbose' configuration of 0 is the default for pgbouncer, and is the least verbose.
**Checklist**
> Decrease PGbouncer logging verbosity

- bin/reset-local-dev
- templates/workers/worker-deployment.yaml
- values.yaml
This PR adds an `initContainer` to the workers to prevent a `Permission Denied` issue on boot when running in KinD using the `local-path` provisioner.
> Add an initContainer to chown worker logs directory

- templates/ingress.yaml
fix multiline annotations indent in values.
```
ingress:
enabled: true
baseDomain: local.astronomer.io
webserverAnnotations:
nginx.ingress.kubernetes.io/server-snippet: "|-\n  location ^~ /api/ {\n    if ($host = ''deployments.local.astronomer.io'' ) {\n      return 404;\n    }\n    proxy_pass http://deployments.local.astronomer.io/airflow/$request_uri\"\n  }"
```
before this PR:
```
UPGRADE FAILED
Error: YAML parse error on airflow/templates/ingress.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key
Error: UPGRADE FAILED: YAML parse error on airflow/templates/ingress.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key
```
> fix multiline annotations indent in values.

- templates/workers/worker-deployment.yaml
forgot this part in https://github.com/astronomer/airflow-chart/pull/68
> user-provided image for DB migration wait

- templates/workers/worker-kedaautoscaler.yaml
Newer versions of KEDA require the TargetQueryValue to be filled.
I've defaulted it to one so that autoscaling will always happen
> Adds TargetQueryValue field to KEDA ScaledObject

- templates/pgbouncer/pgbouncer-networkpolicy.yaml
In new versions of KEDA, the apiserver is a seperate pod
with a different label. This PR adds a networkPolicy that
allows the KEDA apiserver to communicate with pgbouncer
> Add networkPolicy for keda-apiserver

- templates/workers/worker-kedaautoscaler.yaml
- values.yaml
We want to bill based on the maximum *POSSIBLE* workers, so if a user
turns on KEDA autoscaling, they should still be limited based on their
billing
> KEDA maxReplicaCount matches celery worker replicas

- templates/create-user-job.yaml
As my company has been deploying with an internal GCR registry we've found out this imagePullSecrets is missing (all other components, like webserver, scheduler and pods created with KubernetesExecutor can download private images easily)
> Fix imagePullSecrets for create-user-job

- templates/configmap.yaml
After some testing on my minikube and my company infrastructure, we've
found out that the label "kubernetes-executor" (created by this code) usually appears also with
"kubernetes_executor" (created by airflow code). This produces a breakup on our label processing
in prometheus/metrics.
Also detected same anti-pattern on label "kubernetes-pod-operator" (and
"kubernetes_pod_operator"). 
I think it makes sense for this code to be changed to avoid this
duplication.
> Fix duplicate labels "kubernetes-executor" and "kubernetes-pod-operator"

- .circleci/config.yml
- Chart.yaml
- bin/clean-slate
- bin/install-ci-tools
- bin/package
- bin/reset-local-dev
- bin/run-ci
- bin/start-kind-cluster
- templates/scheduler/scheduler-deployment.yaml
In helm 2, extra values in kube YAML are ignored, but in helm 3, it throws an error. 'strategy' is not a valid key for StatefulSetSpec https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#statefulsetspec-v1-apps
this bug was discovered when I was writing the 0.15 regression testing for the pgbouncer issue on commander
> Local executor patch for Helm 3

- templates/flower/flower-service.yaml
- templates/secrets/redis-secrets.yaml
In using this chart outside of the Astronomer platform we noticed that
two places were using the `platform.workspace` that didn't need it.
The broker-url secret is just using it as a label, and that doesn't make
any sense (but also doesn't break anything).
The flower service has it specified in the label selector, so this
service wasn't working if the workspace wasn't provided. For
comparison, the webserver service just has component, release and tier
as its selector.
> Don't use platform.workspace in Reids/Flower resources

- templates/scheduler/scheduler-deployment.yaml
To support running with more than a single scheduler pod we can no
longer rely on `most_recent_job` -- as that would simply select the most
recent row to have beaten, which could be from a different pod.
> Make Scheduler livenessProbe HA ready.

- templates/configmap.yaml
Resolves https://github.com/astronomer/issues/issues/1087
This removes any executor choice logic from the `airflow.cfg` `ConfigMap`. This was causing an issue where the kubernetes namespace was blank when using the KPO. Using the executor for this logic was not enough.
These configs are simply not used if the executor isn't loaded so there should be no harm in having "extra" config loaded.
The only user-facing difference that I can think of will be what users see when they load the "Admin" > "Configuration" menu in Airflow. Users will see that there are configurations set for an executor they are not actually using. Minor thing, but just wanted to call that out.
> Remove helm logic for executor specific configurations

- templates/scheduler/scheduler-deployment.yaml
- values.yaml
- Allows for users to configure scheduler livenessProbe values from the top level `values.yaml`
- Increased timeoutSeconds from `1` to `5`
- Related to https://github.com/astronomer/issues/issues/1496
> Allow for configurable scheduler livenessProbe values

- templates/_helpers.yaml
- values.yaml
If server requires TLS and rejects plain TCP connection, we need ability to configure it.
> add server tls sslmode

- templates/statsd/statsd-deployment.yaml
- values.yaml
I have this running on staging.
grafana: https://grafana.staging.astronomer.io/d/E5LsXoamz/airflow-deployment-overview?orgId=1&refresh=10s&var-deployment=devoid-solar-9786
deployment metrics view: https://app.staging.astronomer.io/w/ck7byis5o07li0915r814ir4c/d/devoid-solar-9786/metrics
> Reduce cardinality of Airflow metrics

- requirements.lock
- templates/create-user-job.yaml
- values.yaml
Our company is using Istio, this is making the _create-user-job_ not being able to end, and also crashing our CD. In order to fix this we are adding a parameter to be able to add an annotation to that job so we can disable the istio sidecar injection.
Issue reported:
- Istio: https://github.com/istio/istio/issues/11045 and https://github.com/istio/istio/issues/6324
- Kubernetes: https://github.com/kubernetes/kubernetes/issues/65502
More details on the issue:
- https://medium.com/redbox-techblog/handling-istio-sidecars-in-kubernetes-jobs-c392661c4af7
Add "sidecar.istio.io/inject": "False" to createUserJobAnnotations
Execute `helm template .`  and search for ## Airflow Create User Job the new annotation added.
> Add code to be able to add annotations to create-user-job

- templates/scheduler/scheduler-deployment.yaml
- templates/webserver/webserver-deployment.yaml
- templates/workers/worker-deployment.yaml
- values.yaml
This is follow up from a customer upgrade where custom environmet variables in the Dockerfile of the user-provided container (custom airflow config for airflow secrets backend) caused issues in the database migration (or wait for migration) steps.
> Don't use custom environment variables in init containers

- templates/_helpers.yaml
This is follow up from a customer upgrade where we found a custom setting in their user-provided image was causing flower to crashloop. The expected behavior is for flower to use the flower image configured rather than the user-provided airflow image.
> Flower deployment should use Flower image

- templates/scheduler/scheduler-deployment.yaml
- templates/webserver/webserver-deployment.yaml
- templates/workers/worker-deployment.yaml
Backporting https://github.com/astronomer/airflow-chart/commit/30070967e698c7c6a29c20f846f03aeb7f4b1413 to `main`.
This is an important commit that was made directly on both `release-0.15` and `release-0.16` but was never cherry-picked to main, so we keep loosing it. This PR ensures that this change persists into future releases.
> Fix init containers to use default airflow version

- tests/secrets_elasticsearch-secret_test.yaml
I was getting both successful and failed runs using the same test. This PR sets the `elasticsearch.connection` value to an object, rather than setting individual fields via dot separations.
This more closely mirrors what we'd pass in via production. I feel like the previous version should have evaluated fine, but it seems like setting the `elasticsearch.connection` to `true`, instead of an object was causing it to flake out occasionally.
> Fix Elasticsearch secret test

- .circleci/config.yml
- .github/pull_request_template.md
- .gitignore
- bin/run-ci
- tests/functional-tests/requirements.txt
- tests/functional-tests/test_chart.py
- values.yaml
- Adding a PR template to make sure we are adding tests when we are merging PRs.
- Adding a place for developers to add more functional testing, started from what we have in ap-airflow
After this, astronomer/astronomer, astronomer/airflow-chart, and astronomer/ap-airflow all will use the same testinfra-based pytest approach for functional testing.
> Add functional testing and PR template

- Chart.yaml
- templates/_helpers.yaml
- templates/create-user-job.yaml
- templates/scheduler/scheduler-deployment.yaml
- templates/webserver/webserver-deployment.yaml
- templates/workers/worker-deployment.yaml
- values.yaml
Updating airflow charts to fix secret synchronization issue
Resolves astronomer/issues#1409
> What are the main risks associated with this change, and how are they …
> Fix secret synchronization

- templates/workers/worker-deployment.yaml
- tests/workers_worker-deployment_test.yaml
- values.yaml
This PR modifies the worker template to allow passing a non-default deployment update strategy to worker deployments, in particular celery workers. The values have been set to allow 100% maxSurge and 50% maxUnavailable allowing new deployments of celery workers to launch a full set of replicas before the old set goes away. Allowing the new workers to pick up work as quickly as possible, rather than the current default which is 1 at a time.
Resolves https://github.com/astronomer/issues/issues/1410
helm chart unit test added.
> Support for modifying celery worker deployment strategy

- values.yaml
Upgraded image to 0.18.0 with the following changes
[ENHANCEMENT] Allow turning off tagging extensions (#325)
[ENHANCEMENT] Add a lifecycle API for configuration reloads and restarts (#329)
In the previous work to improve how/what statsd metrics are collected a handful of them were unintentionally dropped. This PR puts the specific metrics back that Houston UI and our airflow Grafana dashboard are looking for back.
Resolves https://github.com/astronomer/issues/issues/1780
I tested this by deploying an AWS test cluster and running airflow deployments and querying for those metrics and I was getting results.
> Upgrade Statsd Version and Add Additional Statsd Metrics

- .circleci/config.yml
- files/pod-template-file.yaml
- templates/_helpers.yaml
- templates/configmap.yaml
- templates/create-user-job.yaml
- templates/scheduler/scheduler-deployment.yaml
- tests/pod-template-file_test.yaml
- values.yaml
> Add pod_template_file as that is the only way to use K8sExecutor in 2.0

- README.md
`--n` > `-n`
Changed `--n` to `-n`
N/A …
> Fixed typo in helm install command

- .circleci/config.yml
Bump CircleCI machine image to ubuntu-2004:202008-01 and CI python to 3.8.5. Changes only affect CI runs.
The machine image we have been using is being deprecated, and is 4.5 years old. This change modernizes the software running our CI pipelines.
> Update ci machine image to ubuntu-2004:202008-01

- Chart.yaml
Once this is done we will create the 0.18 release branch off this -- this ensures that the version is correct on master (where as previously it was two versions old on master)
> Update version to 0.18.0

- .circleci/config.yml
In #121 we upgraded to a newer CI image and a new python image, but we
didn't fix the release step (as we only noticed it when trying to
release.)
It turns out that the release script doesn't even need python though, so
we can remove this command entirely
> Don't try to use old python on release step

- .circleci/config.yml
Tested via SSH on CircleCI, this gets as far as actually uploading a
file, so hopefully this time it will work.
The perils of fixing bugs in the release process is you can't very easily run this locally.
> Gcloud in the release step does need a python installed

- templates/configmap.yaml
The condition to check SemVer was wrong (`>=` instead of `<=`)
> Fix airflow_local_settings.py for Airflow <=1.10.12

- templates/configmap.yaml
`tolerations` and `affinity` are part of `V1PodSpec` and not `V1ObjectMeta` for Airflow >= 1.10.12
@schnie Do we need to update google-environments too?
> Fix pod_mutation_hook for Airflow >= 1.10.12

- templates/run-airflow-migrations.yaml
- Airflow chart 0.18.0 fails to deploy via astronomer platform due to indentation error in `run-airflow-migrations.yaml`
```
time="2020-10-22T13:32:10Z" level=error msg="YAML parse error on airflow/templates/run-airflow-migrations.yaml: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context" function=InstallDeployment package=kubernetes
```
- We only see this if passing in `.Values.labels` (which astronomer platform will do)
Resolves astronomer/issues#2011
> Fix indent error in run-airflow-migrations

- files/pod-template-file.yaml
- tests/pod-template-file_test.yaml
This change will ensure that every time we update the airflow image,
the pod_template_file will reflect the updated image at launch
> …
> Add image to pod_template_file

- templates/run-airflow-migrations.yaml
> Don't create annotations key if there are no values

- bin/package-and-release
```
$ helm repo update ; helm search repo astronomer-internal/airflow -l --devel --max-col-width 0
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "astronomer-internal" chart repository
...Successfully got an update from the "astronomer" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME                       	CHART VERSION   	APP VERSION	DESCRIPTION
astronomer-internal/airflow	0.18.0          	           	Helm chart to deploy the Astronomer Platform Airflow module
astronomer-internal/airflow	0.18.0-build6613	1.10.10    	2073-improve-release https://circleci.com/gh/astronomer/airflow-chart/6613
```
related to astronomer/issues#2073
> Show branch and CI URL in description field for dev builds

- .circleci/config.yml
- bin/install-ci-tools
- requirements.lock
Switch out deprecated helm repo for new stable repo.
- <https://www.cncf.io/blog/2020/11/05/helm-chart-repository-deprecation-update/>
- <https://helm.sh/docs/faq/#i-am-getting-a-warning-about-unable-to-get-an-update-from-the-stable-chart-repository>
Relates to astronomer/issues#2003
> Update to new helm stable repo

- templates/scheduler/scheduler-deployment.yaml
- tests/scheduler_scheduler-deployment_test.yaml
- values.yaml
Adding support for pod anti-affinity on airflow scheduler pods
Resolves https://github.com/astronomer/issues/issues/1988
Added helm unit test to confirm anti-affinity is exists.
> Adding support for pod anti-affinity on airflow scheduler pods

- Chart.yaml
- templates/airflow-scc-anyuid.yaml
- tests/scc_test.yaml
- values.yaml
Peer programmed with @ianstanton 
Adding support for Openshift Security Context Constraints
Part of https://github.com/astronomer/issues/issues/2039
This configuration is default disabled. For the enabled case, a unit test has been added.
> Adding support for Openshift Security Context Constraints

- files/pod-template-file.yaml
The affinity, nodeselector, and tolerations settings were
indented too far. This was causing failures when platform
affinities were added to the pod
Resolves …
> Fix spacing for affinity

- templates/configmap.yaml
Without this we get lots of deprecation warnings in the logs
> Update chart to use both 2.0 and 1.10 name of config options

- Chart.yaml
- templates/secrets/elasticsearch-secret.yaml
- tests/secrets_elasticsearch-secret_test.yaml
- values.yaml
When integrating with an external elasticsearch cluster, we will use HTTPS instead of HTTP. This change allows configuration of the protocol to use with Elasticsearch
part of https://github.com/astronomer/issues/issues/2074
This was tested manually in practice on an openshift cluster with an external elastic search, and also unit tests are added to ensure that the configuration is set as expected.
> Add screenshots to illustrate the changes, if applicable.
not a default configuration, so can't add functional tests
> Allow configuration of Elasticsearch protocol

- templates/NOTES.txt
Could not test by running the chart locally, as it was failing with the following error `Error: found in Chart.yaml, but missing in charts/ directory: postgresql`
> Add namespace in the port-forward command

- files/pod-template-file.yaml
Fixes bug where pods launched by pod_template_file did not
have access to the airflow.cfg. This was creating issues in sending
logs to ElasticSearch.
solves: astronomer/issues#2141
> Please make the PR title informative to the user experience. For example when adding a feature, say "Add metrics tab for Deployments" instead of "Bump Astro-UI to version X.Y.Z". Bugs are sometimes harder to make customer-facing because they are very detailed, but do what you can. Instead of "Fix metrics cardinality bug" (user does not know what 'cardinality' means and does not matter to them), say "Fix bug slowing down the metrics tab". The PR title will be used for the commit message when it's merged, and these commit messages are used to generate customer-facing …
> Add airflow.cfg to pod_template_file

- templates/configmap.yaml
Slack chat: https://astronomerteam.slack.com/archives/CGQSYG25V/p1605863107155800
We allow users to use `airflow_db` connection for Celery and Local Executor. However, with KubernetesExecutor this env var (`AIRFLOW_CONN_AIRFLOW_DB`) is not found on task PODs.
I have NOT tested this, so let me know if the fix is wrong.
https://github.com/astronomer/airflow-chart/blob/b56350b2f4b8930f6b42cb9064ae55caba6b274b/templates/scheduler/scheduler-deployment.yaml#L90-L94
https://github.com/astronomer/airflow-chart/blob/87e27ad70608a957e7102f30cbac5523a4dbb47e/templates/_helpers.yaml#L54-L66
https://github.com/astronomer/airflow-chart/blob/87e27ad70608a957e7102f30cbac5523a4dbb47e/templates/_helpers.yaml#L2-L20
> Populate airflow_db connection for KubernetesExecutor launched-pods too

- values.yaml
This matches the current default airflow tag used in the chart.
Part of astronomer/issues#2100 -- there will be a companion change in Houston.
> Change default uid/gid to values for Debian image

- Chart.yaml
- files/pod-template-file.yaml
Use UID given by houston, not determined during chart rendering. This fixes permission problems for some edge cases where users have switched from Debian to Alpine.
- <https://astronomerteam.slack.com/archives/CR6JGBCTA/p1606758088112400>
> Correct runAsUser in pod-template-file

- .circleci/config.yml
- templates/rbac/pod-log-reader-role.yaml
- templates/rbac/pod-log-reader-rolebinding.yaml
- values.yaml
Allows webserver to read pod logs for tasks launched by k8sexecutor
without needing an external log store. Note: logs will only be
accessible while the pod is running (or after if you don't delete it)
> Please make the PR title informative to the user experience. For example when adding a feature, say "Add metrics tab for Deployments" instead of "Bump Astro-UI to version X.Y.Z". Bugs are sometimes harder to make customer-facing because they are very detailed, but do what you can. Instead of "Fix metrics cardinality bug" (user does not know what 'cardinality' means and does not matter to them), say "Fix bug slowing down the metrics tab". The PR title will be used for the commit message when it's merged, and these commit messages are used to …
> Allow webserver to read pod logs

- templates/rbac/pod-log-reader-rolebinding.yaml
Webserver logs were note working because we were giving the wrong serviceaccount name to the rolebinding.
> What are the main risks associated with this change, and how are they …
> Add -serviceaccount to rolebinding fix the webserver logging

- Chart.yaml
- files/pod-template-file.yaml
Per @danielhoherd, the [original PR for this ](https://github.com/astronomer/airflow-chart/pull/187) failed CI checks due to it coming from a fork instead of a branch. Daniel created a new branch; this is a PR on that. 
Add fsGroup to the Kubernetes Pod Template definition. The current pod operator template overrides any template from the airflow image and if an IAM credential exists it won't be added with the proper ownership causing issues with it being accessed by the pod
Resolves https://github.com/astronomer/issues/issues/2587
and https://github.com/astronomer/issues/issues/2100
> Add fsgroup for IAM credentials files

- README.md
This chart expects keda version 1.5.0.  Here i update readme to reference it.
closes https://github.com/astronomer/airflow-chart/issues/176
> fix keda version in readme

- templates/rbac/pod-launcher-role.yaml
In order for the KubernetesExecutor to pick up tasks from dead
schedulers, it needs to have the ability to patch existing pods s.t. the
watcher thread can read the pod statuses
> Please make the PR title informative to the user experience. For example when adding a feature, say "Add metrics tab for Deployments" instead of "Bump Astro-UI to version X.Y.Z". Bugs are sometimes harder to make customer-facing because they are very detailed, but do what you can. Instead of "Fix metrics cardinality bug" (user does not know what 'cardinality' means and does not matter to them), say "Fix bug slowing down the metrics tab". The PR title will be used for the commit message when it's merged, and these commit messages are used to generate customer-facing …
> Add patch ability to pod-launcher-role

- templates/configmap.yaml
- tests/configmap_test.yaml
This change uses the same logic for determining image tag on k8s workers
as is used for other Airflow components (e.g. the scheduler).
> Use defaultImageTag for k8s workers

- bin/run-ci
- tests/functional-tests/test_chart.py
- values.yaml
Our new users should use performance improvements in 2.0.0 instead of 1.10.x.
We could also update it to 2.0.1 -- I didn't to avoid accidental update for chart + platform users since we had a bug regarding >= 2.0.0
Resolves astronomer/issues#2722
> Change the default airflow version/tag to 2.0.0

- README.md
- files/pod-template-file.yaml
- templates/scheduler/scheduler-deployment.yaml
- templates/workers/worker-deployment.yaml
- tests/pod-template-file_test.yaml
- tests/scheduler_scheduler-deployment_test.yaml
- tests/workers_worker-deployment_test.yaml
- values.yaml
This adds the ability to provide extra init containers for both the scheduler and workers. It also provides a working example of git-sync.
> Add extraInitContainers and git-sync example

- .circleci/config.yml
- .pre-commit-config.yaml
- tests/scheduler_scheduler-deployment_test.yaml
- tests/webserver_webserver-deployment_test.yaml
- values.yaml
The main purpose of this PR is to bump the docker images in values.yaml to use the latest images that have the latest security fixes. See https://github.com/astronomer/issues/issues/2702
- Bumped version of astronomer images in values.yaml
- Bumped CI kind versions to newer patch releases
- Bumped CircleCI machine image of ubuntu, and its version of python
- Bumped CI version of helm
- Bumped to latest ci-helm-release image
- `pre-commit autoupdate` and improve some configs, which is in line with what is being used elsewhere
- Auto-applied `prettier` formatting to some files via vscode plugin
I have deployed this version of the chart to dev as `airflowChartVersion: 0.18.7-build9321` <https://github.com/astronomer/google-environments/commit/f031e1af3ae25b2bb96211379add8450a83099ec>
> Update docker images. Bump some versions. Auto-formatting.

- files/README.md
- templates/pgbouncer/pgbouncer-networkpolicy.yaml
- tests/pgbouncer_pgbouncer-networkpolicy_test.yaml
- tests/pod-template-file_test.yaml
- values.yaml
* Add pgbouncer.networkPolicies.enabled flag
* Document pod-template-file behavior
* Auto-format via vscode 'prettier' plugin
This should solve https://github.com/astronomer/issues/issues/2516
I've verified that the new tests pass in the quintush fork of helm-unittest which we plan on switching to.
> Add pgbouncer.networkPolicies.enabled flag

- README.md
The old description was outdated. We run with this Helm chart in CI with Kubernetes 1.16+
> Doc: Chart: Update the docs to create Kind cluster

- README.md
- templates/webserver/webserver-deployment.yaml
- tests/webserver_webserver-deployment_test.yaml
- values.yaml
Add `extraVolumes` and `extraVolumeMounts` options to webserver.
Scenario of interest includes being able to mount a client cert/key to authenticate against a remote elasticsearch cluster to display logs.
> Add screenshots to illustrate the changes, if applicable.
> Add extraVolumes and extraVolumeMounts options to webserver

- CONTRIBUTING.md
- tests/README.md
Document how to write unittests so we can refer people to that when we ask them to write tests for their submissions, which has been a big turn off to people who are unfamiliar with testing helm charts.
> Add a doc on how to write helm unitests.

- templates/flower/flower-deployment.yaml
- tests/flower_flower-deployment_test.yaml
- tests/workers_worker-deployment_test.yaml
closes https://github.com/astronomer/issues/issues/1897
Use can now pass the following in `.Values.env`:
```
FLOWER_PURGE_OFFLINE_WORKERS=300
```
Until now these vars were only passed to Airflow Pods (scheduler, webserver & workers)
> Allow passing Environment Variables to Flower

- templates/_helpers.yaml
- templates/redis/redis-networkpolicy.yaml
- templates/redis/redis-service.yaml
- templates/redis/redis-statefulset.yaml
- templates/secrets/redis-secrets.yaml
- tests/airflow_environment_variables_test.yaml
- tests/redis_redis-networkpolicy_test.yaml
- tests/redis_redis-service_test.yaml
- tests/redis_redis-statefulset_test.yaml
- tests/secrets_redis-secrets_test.yaml
- values.yaml
This allows Redis to be disabled and a separate Celery broker to be
configured in its place with `data.brokerUrl` or
`data.brokerUrlSecretName`.
> Add support for using an external Celery broker

- .circleci/config.yml
`python --version --version` is used for cache because it is more descriptive.
```
$ python --version
Python 3.8.5
$ python --version --version
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0]
```
> Add double --version

- .circleci/config.yml
We don't need to run no-commit-to-branch on CI as that ends up failing
when we run precommit on master.
Edit: A little more color: That check is really meant to protect against accidents locally.
> Only run no-commit-to-branch hook locally

- templates/secrets/redis-secrets.yaml
- tests/secrets_redis-secrets_test.yaml
We will create these secrets (if necessary) _even if_ we aren't
currently using CeleryExecutor. As we are relying on the
"pre-install" hack to prevent changing randomly generated passwords,
updating the executor later doesn't give us the opportunity to
deploy them when we need them. We will always deploy them
defensively to make the executor update path actually work.
> Deploy redis secrets regardless of executor

- templates/webserver/webserver-deployment.yaml
EKS 1.17 needs a token in the images to enable role assumption. This PR will ensure the token file is under the right group id and has the proper permissions to be accessed.
Add fsGroup to webserver deployment securityContext
Resolves astronomer/issues#3086
> Add fsGroup to webserver deployment securityContext

- templates/configmap.yaml
Set the proper values for `kubernetes_executor` and
`kubernetes_pod_operator` labels.
This is critical, especially when using 2.0+, KubernetesExecutor, KPO and
`is_delete_operator_pod=False`, as the `kubernetes_executor` label is used
in the completed pod adoption logic in KubernetesExecutor. With the wrong
labels, the executor tries to adopt the task pod.
Before:
```
task:
kubernetes_executor=True                                                                                                                                                                                
kubernetes_pod_operator=False
```
After:
```
task:
kubernetes_executor=False                                                                    
kubernetes_pod_operator=True 
```
And in both cases workers get:
```
worker: …
```
> Fix labels set by pod_mutation_hook

- .circleci/config.yml
- .pre-commit-config.yaml
- Chart.yaml
- Bump kube_versions to what is supported by Astronomer
- Improve pre-commit run syntax
- Bump `black`
- Improve chart description text
- Bump chart version to 0.20.0-rc1, which will be the first version in the release-0.20 branch
> Tweak CI. Bump to 0.20.0-rc1

- templates/scheduler/scheduler-deployment.yaml
Similar to workers, in 2.1.0+ Airflow's scheduler will start a webserver
to serve logs when using a "local" executor.
Closes: #236
> Don't serve_logs in Airflow 2's scheduler

- templates/rbac/pod-cleanup-rolebinding.yaml
- templates/rbac/pod-launcher-rolebinding.yaml
- templates/rbac/pod-log-reader-role.yaml
- templates/rbac/pod-log-reader-rolebinding.yaml
**before this fix:**
```
kubectl apply -f test.yaml
error: unable to decode "test.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Namespace: ReadString: expects " or n, but found 5, error found in #10 byte of ...|mespace":53}}|..., bigger context ...|,"metadata":{"name":"53-build-robot","namespace":53}}|...
cat test.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: 53-build-robot
namespace: 53
```
after fix:
```
kubectl apply -f test.yaml
serviceaccount/53-build-robot created
cat test.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: 53-build-robot
namespace: "53"
```
> allow namespace be an integer

- requirements.lock
- requirements.yaml
Now that the OSS helm chart version 1.2.0 has been released, we should use that instead of our prerelease version.
> Use OSS helm chart version 1.2.0

- .circleci/config.yml
- .pre-commit-config.yaml
- Bump CI runner image tag
- Bump machine image and associated python version references
- Swap out pre-commit shellcheck hook for one that installs shellcheck automatically
- `pre-commit autoupdate`
- Fix a config default that referenced an older kube patch version
> Bump and tweak dev component versions

- values.yaml
Redis Image updated to newer version 
Bump redis image to 6.2.5-1
Resolves https://github.com/astronomer/issues/issues/3721
> Add screenshots to illustrate the changes, if applicable.
> Bump redis image

- Chart.yaml
This PR bumps the current chart version to `1.1.0-rc1` by bumping the OSS chart version to `1.3.0` to allow Dev/QA testing.
The changes in 1.3.0 version of OSS chart from 1.2.0 are documented at https://airflow.apache.org/docs/helm-chart/stable/changelog.html#airflow-helm-chart-1-3-0-2021-11-08
> Bump to the latest released version of OSS Chart: `1.3.0`

- .circleci/config.yml
- .github/pull_request_template.md
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- UPDATING.md
- tests/README.md
- tests/functional-tests/requirements.txt
Add pre-commit hooks that are more in line with what we have in astronomer/astronomer. Also add prettier. Run `pre-commit run --all-files` to correct the contents of the repo.
Also bump some dev component versions in CircleCI.
There are no functional changes in this change set. Closest thing is sorting a requirements.txt file. Other than that and pre-commit config, everything else is just markdown changes, and mostly whitespace.
> Add pre-commit, tweak CircleCI configs

- Chart.lock
Bump airflow chart dependency from 1.2.0 to 1.3.0.
> Bump airflow chart dependency

- values.yaml
> update git sync version to 3.3.4 from 3.3.0 to fix rev git sync param accepting git hash
looked at the following for reference: https://github.com/apache/airflow/blob/1ee65bb8ae9f98233208ebb7918cf9aa1e01823e/chart/values.yaml#L85 
Resolves astronomer/issues#3779
> Please add helm unit testing, if applicable. The docs are regretfully sparse for helm unit testing, [here](https://github.com/astronomer/helm-unittest/blob/main/DOCUMENT.md) is what we have to work with. In general, these kind of tests can be used for specific assertions like 'when these values are set, the resource ends up looking like XYZ' but not for generalized assertions like 'for all resources, make sure the …
> Fix git sync rev param hash cloning issue

- values.yaml
Airflow pre 1.10.12 doesn't use the pod_template_file and we were missing some of the old-style configuration needed to allow KubernetesExecutor to function.
Resolves https://github.com/astronomer/issues/issues/3799
> Please add helm unit testing, if applicable. The docs are regretfully sparse for helm unit testing, [here](https://github.com/astronomer/helm-unittest/blob/main/DOCUMENT.md) is what we have to work with. In general, these kind of tests can be used for specific assertions like 'when these values are set, the resource ends up looking like XYZ' but not for generalized assertions like 'for all resources, make sure the namespace is not set to the release name'.
> Please …
> Fix KubernetesExecutor on Airflow < 1.10.12

- bin/release-internal-to-prod
Issue: https://github.com/astronomer/issues/issues/3816
Description: when the chart file has a field called version twice the awk command concats them together. for instance the below chart outputs 1.0.91.3.0 when it should output 1.0.9.
`# apiVersion v2 is Helm 3
apiVersion: v2
name: airflow
version: 1.1.0-rc1
description: Helm chart to deploy the Astronomer Platform Airflow module
icon: https://airflow.apache.org/docs/apache-airflow/stable/_images/pin_large.png
keywords:
\- astronomer
\- airflow
dependencies:
\- name: airflow
version: 1.3.0
repository: https://airflow.apache.org`
> fix release to prod command for multi version charts

- .circleci/config.yml
- bin/install-ci-tools
Synchronize the tested k8s versions with what we have in astronomer/astronomer
These changes were all made while troubleshooting problems with kind cluster creation with 1.21, but kind itself ended up being the problem as it was too old for 1.21.
- Bump kind version
- Bump helm version
- Bump machine version and pyenv version to match the new machine
> Sync supported k8s versions with what is in astronomer/astronomer

- templates/airflow-scc-anyuid.yaml
Allows nfs volumes to be mounted directly in airflow pods on OpenShift
This allows users to mount nfs volumes using the `extraVolumes` feature on Openshift (in the current configuration this is blocked by security context contraints).
There are security implications to allowing extra volume types although in this case since this doesn't allow extra access to the host it appears to me to be minimal.
> Add NFS as an allowed volume type to airflow-scc-anyuid

- Chart.lock
- Chart.yaml
Use the custom 1.3.1 astro-oss based Airflow chart, which supports installing in environments without outbound networking.
> Use custom astro-OSS 1.3.1 airflow chart

- dev/custom_upstream_airflow_chart_release.md
On occasion, `airflow-chart` will need to use a custom release of the official community Airflow chart (e.g. to fix a bug quickly). This document describes that process.
> Document how to release custom upstream Airflow chart

- .circleci/config.yml
Deprecate k8s 1.17 because in January it will [no longer be supported in any supported cloud provider](https://github.com/astronomer/ops-stuff/blob/main/docs/k8s-version-table.md)
Please squash and merge when approved.
> Deprecate k8s 1.17

- values.yaml
bump redis image to 6.2.6
bump redis image to 6.2.6
Resolves astronomer/issues#3947
NA
> Add screenshots to illustrate the changes, if applicable.
> bump redis image to 6.2.6

- .github/pull_request_template.md
We changed the PR template in astronomer/astronomer to vastly reduce the clutter that is left untouched most of the time. I think it's been good and we should put the same template here.
> Change PR template to the same as what is in astronomer/astronomer

- templates/_helpers.yaml
Add COMPONENT env. var. to standard Airflow environment. This is consumed by the ap-airflow entrypoint when sidecar logging is enabled.
astronomer/issues#3563
> Add COMPONENT env. var. to standard Airflow environment

- bin/lint
- templates/generate-ssl.yaml
- tests/chart_tests/helm_template_generator.py
- tests/chart_tests/test_pgbouncer_certgenerator.py
- values.yaml
Adds support for sslmode "require" when posgtres server is enabled with force tls
pbouncer sslmode support
Resolves https://github.com/astronomer/issues/issues/3482
> Please add helm unit testing, if applicable. The docs are regretfully sparse for helm unit testing, [here](https://github.com/astronomer/helm-unittest/blob/main/DOCUMENT.md) is what we have to work with. In general, these kind of tests can be used for specific assertions like 'when these values are set, the resource ends up looking like XYZ' but not for generalized assertions like 'for all resources, make sure the namespace is not set to the release name'.
> Please also add to the system testing …
> pgbouncer sslmode support

- .circleci/config.yml
- .pre-commit-config.yaml
- bin/start-kind-cluster
- tests/chart_tests/helm_template_generator.py
Drop k8s 1.18 from this repo. It is being deprecated in all cloud environments within the next month and we are not supporting it in new versions of astronomer.
https://github.com/astronomer/issues/issues/3890
These are all CI related changes so as long as CI is passing we should be good.
> Drop k8s 1.18

- values.yaml
Certificates are not generated due to permission issues - introduced by uid ranges that was not considered initially for openshift
https://github.com/astronomer/issues/issues/4223
> fix for pgbouncer client certs generation issue with openshift

- templates/generate-ssl.yaml
- tests/chart_tests/helm_template_generator.py
- tests/chart_tests/test_default_chart.py
resolves https://github.com/astronomer/issues/issues/3885
```
astronomer-houston-worker-776c89bfc5-6ztvm houston 2022-02-09T18:37:08 INFO Response from #createDeployment: {"result":{"message":"failed pre-install: warning: Hook pre-install airflow/templates/generate-ssl.yaml failed: RoleBinding in version \"v1beta1\" cannot be handled as a RoleBinding: v1beta1.RoleBinding.Subjects: []v1beta1.Subject: v1beta1.Subject.Namespace: ReadString: expects \" or n, but found 1, error found in #10 byte of ...|mespace\":12345}]}\n|..., bigger context ...|name\":\"test-number-ns-pgbouncer-ssl\",\"namespace\":12345}]}\n|..."},"deployment":{}}
```
> Add properly quote namespace names

- .circleci/config.yml
- bin/install-ci-tools
- values.yaml
* ap-pgbouncer 1.8.1 -> 1.16.1
* ap-pgbouncer-exporter 0.11.0-1 -> 0.13.0
* ap-redis 6.2.5-1 -> 6.2.6
Do not merge this PR until this description is replaced with relevant info.
Do not merge this PR until this text is replaced with links to related issues.
> bump release 0.20 images

- .circleci/config.yml
- Chart.yaml
- bin/install-ci-tools
- values.yaml
**backport vendor packages to release_1_0**
* ap-redis 6.2.5-1 -> 6.2.6
* ap-pgbouncer 1.16.0 -> 1.16.1
* ap-pgbouncer-exporter 0.11.0-2 -> 0.13.0
**additional changes**
migrate k8s.gcr.io/git-sync/git-sync to astronomer quay.io/astronomer/ap-git-sync
update git-sync image version 3.3.4 -> 3.3.5
**circle ci config updates**
* updates to kind package version
* ci image version update
* helm release image version update
* circleci ubuntu image version update
* set python to 3.9.7
Issue Link : https://github.com/astronomer/issues/issues/4210
QA should able to deploy airflow deployment without any issues
> backport ap-vendor security updates to release-1.0 airflow chart

- .circleci/config.yml
- Chart.yaml
- bin/install-ci-tools
- values.yaml
**backport vendor packages to release_1_1**
* ap-redis 6.2.5-1 -> 6.2.6
* ap-pgbouncer 1.16.0 -> 1.16.1
* ap-pgbouncer-exporter 0.11.0-2 -> 0.13.0
**additional changes**
migrate k8s.gcr.io/git-sync/git-sync  to astronomer quay.io/astronomer/ap-git-sync
update git-sync image version 3.3.4 -> 3.3.5
**circle ci config updates**
* updates to kind package version
* ci image version update
* helm release image version update
* circleci ubuntu image version update
* set python to 3.9.7
Issue Link: https://github.com/astronomer/issues/issues/4179
QA should able to deploy airflow deployment without any issues
>  backport ap-vendor security changes to release-1.1 airflow chart

- .circleci/config.yml
- templates/generate-ssl.yaml
- templates/ingress.yaml
Update api versions to be compatible with k8s >= 1.22
[Part of work to support Kubernetes 1.22](https://github.com/astronomer/issues/issues/3889)
[Astronomer Airflow Chart Issue Link to support 1.22](https://github.com/astronomer/issues/issues/4363)
- Initial Validation: Added 1.22 k8s kind cluster to run Airflow deployments 
- CI passes on 1.22 and 1.23
> Update deprecated api groups for Kubernetes 1.22 support

- tests/chart_tests/helm_template_generator.py
Helm 3.8 enforces a regex that has been around for a while where release names have to be lower case.
<https://github.com/astronomer/issues/issues/4124>
This same change has already been merged in astronomer/astronomer.
> Lowercase RELEASE-NAME for helm 3.8 compatibility

- templates/workers/worker-persistentvolume.yaml
This fixes the report of a volume template bug made in https://github.com/astronomer/astronomer/issues/1244
I manually tested this. You can see my comment about digging into the bug and what the fix is here: https://github.com/astronomer/astronomer/issues/1244#issuecomment-1076944297
This would have been caught by pytest chart tests that exist in newer versions of the chart. astronomer/airflow-chart version 0.20 is used by astronomer/astronomer version 0.25, which is an LTS. We may want to back-port pytest tests to that version since [we plan to support astronomer/astronomer version 0.25 until December 2022](https://docs.astronomer.io/software/release-lifecycle-policy/#software-lifecycle-schedule). This could be a good learning exercise for new folks on the team, and likely wouldn't take …
> 1244 fix additional volume template

- .pre-commit-config.yaml
- values.yaml
Enhancement to pgbouncer service and various security fixes
* update ap-pgbouncer 1.16.1 -> 1.17.0
* ap-pgbouncer-exporter 0.13.0 -> 0.13.0-1
NA
QA should able to perform deploy and upgrade without any issues
> update vendor images in airflow chart

- README.md
As a first time user for the local deployment of Airflow in KinD cluster, the Airflow login creds were not mentioned in the README
NA
README change
> Documentation | Add default creds to login local KinD airflow deployment

- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/test_logging_sidecar.py
- values.yaml
This PR updates the current sidecar logging template by replacing fluentd configmap with a vector configmap for elastic search consumer
Related astronomer/issues#4419
Tested on a kind cluster
> update sidecar logging template - replace fluentd with vector elasticsearch configmap

- bin/package-and-release-internal
[git.io is shutting down on Friday](https://github.blog/changelog/2022-04-25-git-io-deprecation/). This change removes the short URL and just uses the long URL. 
https://github.com/astronomer/issues/issues/4564
This is a very small change that is only related to CI. No testing is needed if CI passes.
This change should be merged to every branch we support.
> Use the long URL since git.io is shutting down.

- .gitignore
- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/conftest.py
- tests/chart_tests/test_logging_sidecar.py
- This PR overrides vector's global timestamp field type from string to type timestamp. Due to this the ES query that renders Airflow UI and Astronomer UI logs were failing to be fetched.
- This also creates a unique index per sidecar-container. Currently all container logs were written to a default index 
Related https://github.com/astronomer/issues/issues/4575
Tested on remote cluster
0.29.0
> override timestamp key type from string to timestamp

- .gitignore
- Chart.yaml
- tests/chart_tests/test_default_chart.py
- tests/chart_tests/test_redis.py
Add securityContext for redis sts to run as non-root
https://github.com/astronomer/issues/issues/3348
This includes tests, which should be enough, as long as CI passes.
This is just for release 1.6.
> Add securityContext for redis sts to run as non-root

- values.yaml
Turns out it was `elasticsearch_log_id_template` until 1.10.4, then was
deprecated until 2.0.0, when even backcompat was removed. 2+ relied on
the OSS chart's `log_id_template`, which matched our overridden value.
I guess `release-1.6` will eventually be merged into `main`? I'm out of the loop on the branching/merging strategy here.
> Fix Elasticsearch log_id_template

- .helmignore
A lot of extra files are being included in our helm chart. These additions keep the helm chart more tidy and a bit smaller file size.
```
$ k -n astronomer-redacted-redactination-123 get secret "sh.helm.release.v1.redacted-redactination-123.v42" -o jsonpath='{.data.release}' | base64 -d | base64 -d | gzip -d | jq '.chart.files[].name'
2022-06-17T14:48:07-0700
".circleci/config.yml"
".github/pull_request_template.md"
".helmignore"
".pre-commit-config.yaml"
"CODEOWNERS"
"CONTRIBUTING.md"
"LICENSE"
"Makefile"
"README.md"
"UPDATING.md"
"dev/custom_upstream_airflow_chart_release.md"
"tests/README.md"
"tests/__init__.py"
"tests/chart_tests/__init__.py"
"tests/chart_tests/conftest.py"
"tests/chart_tests/helm_template_generator.py"
"tests/chart_tests/requirements.in" …
```
> Exclude a bunch of unrelated repo data from the chart.

- Chart.lock
- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/test_logging_sidecar.py
- values.yaml
Loads external vector config from secrets if customConfig flag is enabled
https://github.com/astronomer/issues/issues/4733
0.29.2
> added condition based on custom config

- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/test_logging_sidecar.py
A change to previous implementation (https://github.com/astronomer/airflow-chart/pull/332) to load entire configmap only if loggingSidecar: customConfig is disabled, else load from secret using configsyncer
https://github.com/astronomer/issues/issues/4733
Houston - https://github.com/astronomer/houston-api/pull/1154
Astronomer - https://github.com/astronomer/astronomer/pull/1575
Tested on kind cluster
0.29.2
> updated condition to load vector configmap

- values.yaml
Removes unused config flag under loggingSidecar 
https://github.com/astronomer/issues/issues/4733
0.29.2
> removed unused config var

- Chart.lock
- Chart.yaml
- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/test_logging_sidecar.py
- values.yaml
A change to previous implementation (https://github.com/astronomer/airflow-chart/pull/332) to load entire configmap only if loggingSidecar: customConfig is disabled, else load from secret using configsyncer
https://github.com/astronomer/issues/issues/4733
Houston - https://github.com/astronomer/houston-api/pull/1154
Astronomer - https://github.com/astronomer/astronomer/pull/1575
> sync vector changes to release 1.6 branch

- .pre-commit-config.yaml
- tests/chart_tests/helm_template_generator.py
- tests/chart_tests/requirements.in
- tests/chart_tests/requirements.txt
- tests/chart_tests/test_pgbouncer.py
- tests/functional-tests/requirements.txt
- Test that `server_idle_timeout` can be set via `airflow.pgbouncer.extraIni`
- Fix inability to `--show-only` on sub-charts 🎉
- Update pre-commit
- remove `pytest-sugar` because it's old and has problems the author doesn't seem interested in fixing.
- Regenerate test dependencies.
- https://github.com/astronomer/issues/issues/4813
These are tests, so nothing else needs to be done.
This should be merged into all supported releases.
> 4813 pgbouncer server idle timeout

- values.yaml
Adds CVE fixes and base image imporvements
image | old | new
-- | -- | --
ap-statsd-exporter | 0.22.4 | 0.22.7 |
ap-pgbouncer          | 1.17.0-2 | 1.17.0-3 |
ap-pgbouncer-exporter  |0.13.0-3 |  0.13.0-4 |
https://github.com/astronomer/issues/issues/4877
NA
cherry-pick to release-1.6 and 1.7
> update vendor packages

- Chart.yaml
- values.yaml
Backport security fixes for vendor images 
image | old | new
-- | -- | --
ap-statsd-exporter | 0.22.4 | 0.22.7 |
ap-pgbouncer          | 1.17.0-2 | 1.17.0-3 |
ap-pgbouncer-exporter  |0.13.0-3 |  0.13.0-4 |
https://github.com/astronomer/issues/issues/4877
> Backport securityfixes rel1 6

- templates/logging-sidecar-configmap.yaml
Initially we processed all message via single transform with remap , that was causing json errors in multiple components even-though it was not valid issue. 
The change added in this PR will filter logs based on components and process the logs , this has fixed parse error  for  webserver, scheduler and trigger components
continuation from the below issue https://github.com/astronomer/issues/issues/4648
Yet to update
cherry-pick to 1.7, 1.6( not yet confirmed)
> update logging sidecar template

- Chart.yaml
- templates/logging-sidecar-configmap.yaml
- values.yaml
- added enhancements to sidecar logging template
- multiple cve fixes for vendor packages
https://github.com/astronomer/issues/issues/4648
QA should now able to get proper logs for worker.
Not error logs will be displayed on web server, scheduler , triggerer services 
cherry-pick to release-1.7
> sync master branch to release-1.7

- templates/logging-sidecar-configmap.yaml
* logs were not displaying for local executor due to the way we parse the logs , that has been fixed with this change
https://github.com/astronomer/issues/issues/4958
QA should able to see airflow logs in airflow deployments UI if local executor is selected
merge to release-1.7
> fix local executor logs

- Chart.yaml
- templates/logging-sidecar-configmap.yaml
logs were not displaying for local executor due to the way we parse the logs , that has been fixed with this change
https://github.com/astronomer/issues/issues/4958
QA should able to see airflow logs in airflow deployments UI if local executor is selected
merge to release-1.7
> pgvishnuram/sync master branch/release 1.7

- values.yaml
image | old | new
-- | -- | --
ap-pgbouncer                   |  1.17.0-3    |  1.17.0-4
ap-pgbouncer-exporter   |  0.13.0-4   |  0.13.0-5
ap-git-sync                       |  3.5.0         |  3.6.1
https://github.com/astronomer/issues/issues/4993
https://github.com/astronomer/issues/issues/4998
cherry-pick to possibly all applicable release branches
> update astronomer airflow vendor images

- Chart.yaml
- values.yaml
Fix security CVE in airflow helm chart release 1.4 
image | old | new
-- | -- | --
ap-statsd-exporter |  0.18.0  | 0.22.7 
ap-pgbouncer.    | 1.17.0-1 | 1.17.0-4
ap-pgbouncer-exporter | 0.13.0-2 | 0.13.0-5 
ap-git-sync | 3.3.5 | 3.6.1
https://github.com/astronomer/issues/issues/5004
QA should verify all components are working fine with platform
merge to release branch 1.4
> fix security CVE in release 1.4

- values.yaml
fix CVE-2022-40674
https://github.com/astronomer/issues/issues/5065
QA should validate pgbouncer service should work as expected
cherry-pick to all valid release branches
> update pgbouncer images

- Chart.yaml
- values.yaml
fix CVE-2022-40674 in pg-bouncer and pg-bouncer exporter service 
https://github.com/astronomer/issues/issues/5065
NA 
cherry-picked to release-1.6 branch
> release 1.6 - backport CVE fixes

- values.yaml
fix CVE-2022-40674
https://github.com/astronomer/issues/issues/5065
QA should validate pgbouncer service should work as expected
This is only for release-1.4 branch.
> update pgbouncer images (#359)

- templates/git-sync-relay/git-sync-relay-deployment.yaml
- tests/chart_tests/test_git_sync_relay_deployment.py
- values.yaml
- Add a livenessProbe health check to the git-daemon container to make sure it is exporting the git repo.
- Use latest git-daemon and git-sync image versions.
https://github.com/astronomer/issues/issues/5145
We should test this in a cluster by deleting the `/git/.git/git-daemon-export-ok` file and making sure the healthcheck puts it back. The healthcheck will fail if it is unable to touch the file, which serves as double duty for auto-healing and also alerting when it cannot achieve a healthy state.
Edit: Verified that this new livenessProbe is working as expected, keeping the git dir exported.
Edit: Verified that the new images with non-verbose work as expected.
This should be merged into all branches that support git-sync-relay.
> 5145 git-daemon healthcheck

- .circleci/config.yml
- bin/install-ci-tools
Stop testing on deprecated versions of k8s. Start testing on 1.24.
- https://github.com/astronomer/issues/issues/5179
- https://github.com/astronomer/issues/issues/5148
- https://github.com/astronomer/issues/issues/5177
As long as CI is passing we should be good.
This should be merged into all supported 1.x branches. 0.20 is only used by astronomer/astronomer 0.25, which we are leaving as is.
> Drop 1.19, 1.20. Add 1.24.

- .gitignore
- .pre-commit-config.yaml
- bin/package-and-release-internal
- bin/repo-state-report.sh
Add repo and CI metadata to helm package.
Also fix a minor pre-commit bug that began blocking CI.
https://github.com/astronomer/issues/issues/5152
```
$ helm pull astronomer-internal/airflow --version 1.7.1-build18945
$ tar -xzf airflow-1.7.1-build18945.tgz
$ cat air
airflow/                      airflow-1.7.1-build18945.tgz
$ cat airflow/repo_state.log
Build time:  2022-11-14T23:35:43+0000
Git repo:    git@github.com:astronomer/airflow-chart.git
Git branch:  5152-add-repo-state-report
Git SHA:     834fcac32b61512354dee2e412461f44fb1aba7e DIRTY
CircleCI Build URL:       https://circleci.com/gh/astronomer/airflow-chart/18945
CircleCI Build Number:    18945
CircleCI Repository URL:  git@github.com:astronomer/airflow-chart.git
CircleCI SHA1: …
```
> Add repo state report

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- .pre-commit-config.yaml
- tests/__init__.py
Stop testing all k8s versions in every CI run, like we do in astronomer/astronomer: only test the newest and oldest version.
https://github.com/astronomer/issues/issues/5180
These are all CI changes, so no further testing is needed if CI passes.
Merge into all supported branches.
> 5180 only test some k8s versions by default

- Chart.lock
- Chart.yaml
- tests/chart_tests/helm_template_generator.py
- tests/chart_tests/test_default_chart.py
- Switch back to OSS helm chart as a dependency
- Tweak default docs length to 29 for OSS statsd additions
- Remove redundant `--namespace` flag in `helm_template_generator()`
https://github.com/astronomer/issues/issues/5224
There were some statsd additions in the OSS helm chart so we should make sure those don't break anything. There may be other changes in OSS helm chart to look out for.
This should be merged to all branches that use 1.7.0-astro
> 5224 switch back to oss airflow chart

- Chart.yaml
Version 1.7.3. (rc1 was done in release-1.7 branch.)
~Blocked by <https://github.com/astronomer/airflow-chart/pull/375>~
N/A
Testing was done on airflow-chart 1.7.3-rc1 for astronomer 0.31.0 release.
Merge into release-1.7 branch (there will be conflicts)
> version 1.7.3

- templates/_helpers.yaml
We override the OSS `standard_airflow_environment` template to add our own env var. We have a [nice comment](https://github.com/astronomer/airflow-chart/blob/56f6218b6ac8c9246988ea90e20704f93a707c9b/templates/_helpers.yaml#L11) to "keep them in sync", but nothing is checking we do!
Starting with 2.4.0, the celery result backend config is optional, thus the OSS chart has started omitting it. The secret is no longer created by default, but our override doesn't have the logic to skip adding the env var.
e.g:
https://github.com/apache/airflow/blob/14dfc60c949fd572a68b0b069462a0c9a2f88453/chart/templates/_helpers.yaml#L77-L93
Airflow component will be unavailable. pod errors like `Error: secret "airflow-airflow-result-backend" not found` will show in the log.
This is impacting at least one …
> Bring env vars up to date with OSS chart

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- .pre-commit-config.yaml
- bin/install-ci-tools
- bin/start-kind-cluster
- values.yaml
- Use new components that have ap-base 3.16.3
- Update many dev component versions
- https://github.com/astronomer/issues/issues/5291
We'll need to check that pgbouncer and its stats are working, and that git-sync is working.
Merge only to release-1.7 due to git-sync-relay changes being included, which are not supported prior to 1.7. Release a new version after merging.
> ap-base 3.16.3

- docs/git-sync-relay.md
- values.yaml
Improve docs to avoid confusion related to the core git-sync feature, and other small improvements. This is in response to the issue in this thread:
- <https://astronomer.slack.com/archives/C02NZELT2/p1671464975671469>
- <https://apache-airflow.slack.com/archives/C03T0AVNA6A/p1671450081264109>
N/A
Only docs changes, no testing is needed. I did set up a kind cluster and test these instructions out while changing them.
Because these are only docs changes, the only CI step that needs to pass is run_pre_commit
Merge everywhere git-sync-relay is supported.
> Improve docs to avoid confusion related to the core git-sync feature

- values.yaml
Turns out it was `elasticsearch_log_id_template` until 1.10.4, then was deprecated until 2.0.0, when even backcompat was removed. 2+ relied on the OSS chart's `log_id_template`, which matched our overridden value.
No testing needed. This was already merged to release-1.7
This is only meant for master.
> Fix Elasticsearch log_id_template (#326)

- values.yaml
Turns out it was elasticsearch_log_id_template until 1.10.4, then was deprecated until 2.0.0, when even backcompat was removed. 2+ relied on the OSS chart's log_id_template, which matched our overridden value.
> Support ES log_id_template (#326) (#385)

- Makefile
- tests/enable_all_features.yaml
Add the same `make show-docker-images` target that Astronomer "Software" has.
https://github.com/astronomer/issues/issues/4145
N/A, this is just a make target that is not used anywhere yet and only reports data that exists in the repo.
Merge to all supported branches.
> Add the 'make show-docker-images' target from Astronomer "Software"

- .circleci/config.yml
- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/test_logging_sidecar.py
- values.yaml
current vector index format for elasticsearch is set to create daily. This current change helps users to override the default to choose their own index timestamp 
https://github.com/astronomer/issues/issues/5276
https://github.com/astronomer/issues/issues/5277
Added static test case to validate the template
cherry-pick/merge to release-1.7
> allow customization of index time format

- Chart.yaml
Update airflow upstream helm chart to 1.8.0 to get newer features and updates
https://github.com/astronomer/issues/issues/5430
QA should able to deploy airflow from astronomer without any issues, additionally this chart now supports pgbouncer replicas support - now those can be overridden .
cherry-pick changes to release-1.8.
> update upstream airflow helm chart 1.8.0

- tests/chart_tests/test_git_sync_relay_configmap.py
- values.yaml
Add all public keys for github and gitlab with links to where the info is posted, though it can also be found via ssh-keyscan, which is also noted in the comments.
- <https://github.com/astronomer/issues/issues/5488>
None needed. This is is just data additions, not code changes.
This should be merged to all supported branches.
> Add all public keys for github and gitlab

- tests/chart_tests/test_git_sync_relay_configmap.py
- values.yaml
Add new github rsa key due to https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key
N/A, but this key was just added earlier this week in https://github.com/astronomer/airflow-chart/pull/410 so it can be considered as part of https://github.com/astronomer/issues/issues/5488
No testing needed, all needed testing is covered by unit tests.
This should be merged everywhere.
> Add new github rsa key

- templates/logging-sidecar-configmap.yaml
- Only parse json lines as json, pass all other messages straight through.
- Rename transform_syslog to transform_airflow_logs to be more accurate
- <https://github.com/astronomer/issues/issues/5060>
I have tested this in aws with kubernetes executor and verified that the vector parse error messages no longer show up. 
This should be merged everywhere.
> Improve vector log parsing

- templates/git-sync-relay/git-sync-relay-networkpolicy.yaml
Fix a bug in the git-sync-relay networkpolicy where the tier was specified as astronomer instead of airflow.
https://github.com/astronomer/issues/issues/5574
I tested this manually in AWS. I didn't had any unit tests because nothing here is variable, it was just a misconfiguration.
This should be merged to 0.32 and 0.31 since 0.30 does not have git-sync-relay.
> Fix git-sync-relay networkpolicy spec.podSelector.matchLabels.tier

- values.yaml
| Image Name  | Old Tag          |.      New Tag |
| ------------- | ------------- |------------- |
|  ap-statsd-exporter | 0.22.7  |         0.23.1    |
| ap-pgbouncer.         |  1.17.0-8 |    1.18.0-2 |
| ap-git-sync         |  3.6.4-2 |    3.6.5 |
| ap-vector               | 0.26.0 | 0.28.2-1|
| ap-certgenerator | 0.1.2 | 0.1.5|
| ap-git-daemon | 3.16.3 | 3.16.5 |
| ap-pgbouncer-exporter | 0.13.0-9 | 0.13.0-13 |
https://github.com/astronomer/issues/issues/5579
https://github.com/astronomer/issues/issues/5565
QA should able to deploy chart without any issues 
cherry-pick to release 1.8 branch .
> update vendor packages for airflow chart

- templates/logging-sidecar-configmap.yaml
Fix the scheduler logs having a null message field.
https://github.com/astronomer/issues/issues/5060
I have manually tested this on my workstation. Slack thread with some of those details here: <https://astronomer.slack.com/archives/C04JELRC6J3/p1682027094695459>
This should be merged into release-1.8. It looks like the prior changes have not been merged into release-1.7, but if we do that then these changes should also come along.
> Fix scheduler null message field

- templates/git-sync-relay/git-sync-relay-networkpolicy.yaml
Updating gitsync network policy to remove namespace matchLabel Selector and only use podlablel selector
Need to reference git-sync network policy ticket here 
QA should able to deploy airflow with gitsync service and able to use that service from worker , scheduler and triggerer without issues 
cherry-pick to release-1.8
> update gitsync network policy in airflow chart

- templates/generate-ssl.yaml
- tests/chart_tests/test_pgbouncer_certgenerator.py
- values.yaml
Add extraAnnotations to certgenerator. This is primarily so we can cause this workload to run on specific nodes.
https://github.com/astronomer/issues/issues/5610
Unit tests are included, but we should verify that the annotations show up in an e2e test by specifying them in the values and making sure the pod that is generated by the job has the correct annotations.
This should be merged everywhere.
> Add extraAnnotations to certgenerator

- Chart.lock
- values.yaml
sync airflow chart version with release and backport commits needed for 1.7
https://github.com/astronomer/issues/issues/5633
QA should able to deploy airflow chart without issues 
cherry-pick to release-1.7
> fix chart version and missing commits

- templates/generate-ssl.yaml
- tests/chart_tests/test_pgbouncer_certgenerator.py
- values.yaml
Add ability to specify affinity for certgenerator workload.
https://github.com/astronomer/issues/issues/5610
Unit tests are included, which includes a jsonschema check for valid k8s spec, which is good. Better would be to actually check this in an e2e test by setting up the required k8s node annotations.
This should be merged into all supported branches.
> Add certgenerator affinity

- Chart.yaml
- values.yaml
git-sync relay improvements
https://github.com/astronomer/issues/issues/5665
QA should able to deploy git sync relay service without any issues 
cherry-pick to release-0.32
> update git sync relay and airflow version

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- bin/install-ci-tools
Adds support for k8s 1.27 for CI testing
https://github.com/astronomer/issues/issues/5702
> add k8s 1.27 CI support

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- README.md
- tests/__init__.py
- tests/k8s_schema/v1.27.0-standalone/configmap-v1.json
- tests/k8s_schema/v1.27.0-standalone/deployment-apps-v1.json
- tests/k8s_schema/v1.27.0-standalone/ingress-networking-v1.json
- tests/k8s_schema/v1.27.0-standalone/job-batch-v1.json
- tests/k8s_schema/v1.27.0-standalone/networkpolicy-networking-v1.json
- tests/k8s_schema/v1.27.0-standalone/role-rbac-v1.json
- tests/k8s_schema/v1.27.0-standalone/rolebinding-rbac-v1.json
- tests/k8s_schema/v1.27.0-standalone/secret-v1.json
- tests/k8s_schema/v1.27.0-standalone/service-v1.json
- tests/k8s_schema/v1.27.0-standalone/serviceaccount-v1.json
- tests/k8s_schema/v1.27.0-standalone/storageclass-storage-v1.json
- Deprecate 1.22
- Add some missing 1.27 stuff
- ci-helm-release:2023-07
https://github.com/astronomer/issues/issues/5704
These are test changes so no manual testing is needed.
Merge to all supported branches.
> Deprecate k8s 1.22

- Chart.lock
- Chart.yaml
- Use apache/airflow chart version 1.11.0 with cron job template change
- Bump to version 1.9.0 because of the big dependency jump (our chart version does not correlate to the OSS chart version)
https://github.com/astronomer/issues/issues/5670
We will need to be on the lookout for changes in airlfow deployments. I have looked at the change list between 1.8.0 and 1.11.0-astro and nothing big jumped out at me, but we should be diligent since we have been bitten by OSS airflow chart changes in the past.
This should be merged into 0.33.0, probably 0.32.0 too.
> Chart version 1.9.0 with apache/airflow chart 1.11.0-astro

- tests/chart_tests/test_triggerer.py
- values.yaml
upstream OSS chart added config to clean triggerer logs by adding trigger log groomer. Our custom images have different location to run script. This PR adds correct location to run the cleanup script  
https://github.com/astronomer/issues/issues/5720
QA should able to see trigger container should run without any crashes
cherry-pick to release-1.9 branch
> update sidecar triggerer args

- Chart.yaml
update airflow chart 1.9.0 -> 1.9.1 
https://github.com/astronomer/issues/issues/5720
gitsync image update issue -> https://github.com/astronomer/issues/issues/5689
pgbouncer-exporter issue -> https://github.com/astronomer/issues/issues/5316
QA should able to validate all airflow chart with all features working fine.
cherry-pick to release 1.9
> update airflow chart version 1.9.1

- Chart.yaml
- values.yaml
Includes fixes for worker pod liveliness probe failure 
https://github.com/astronomer/issues/issues/5742
QA should able to validate worker pod should work as usual without any probe failures
cherry-pick to release 1.9 branch
> update airflow chart version 1.11.1 for base 1.9

- .pre-commit-config.yaml
- Chart.lock
- Chart.yaml
- tests/chart_tests/test_triggerer.py
- values.yaml
- Update apache/airflow chart to 1.11.1-astro
- Update some pre-commit hooks
- https://github.com/astronomer/issues/issues/5670
- https://github.com/astronomer/issues/issues/5762
This is a big airflow-chart bump so we should be extra alert when testing this.
This is only meant for release-0.32
- Slack discussion: <https://astronomer.slack.com/archives/C04JELRC6J3/p1692700328407509>
> airflow-chart v1.8.8

- .pre-commit-config.yaml
- values.yaml
| imageName | oldTag | newTag |
|--------|--------|--------|
| ap-statsd-exporter | 0.23.1 | 0.24.0 |
| ap-redis | 6.2.7 | 6.2.13 |
| ap-pgbouncer | 1.17.0-10 | 1.20.1 |
| ap-pgbouncer-exporter | 0.14.0-1 | 0.15.0-2 |
| ap-git-sync| 3.6.8 | 3.6.9 | 
| ap-vector| 0.28.2-1 | 0.32.2|
| ap-git-daemon | 3.16.5| 3.18.3 |
| ap-certgenerator | 0.1.5 | 0.1.6|
https://github.com/astronomer/issues/issues/5874
https://github.com/astronomer/issues/issues/5870
https://github.com/astronomer/issues/issues/5855
QA should able to deploy airflow and upgrade redis without any issues
cherry-pick to all valid release branches
> update vendor packages in airflow chart

- Chart.yaml
- tests/chart_tests/test_standardnaming_config.py
- values.yaml
currently our astronomer/airflow-chart is pointed to custom airflow release, this PR re-points the chart to use oss chart.
we are retaining ```useStandardNaming``` to use old format naming in our chart to avoid issues while upgrade 
https://github.com/astronomer/issues/issues/5895
QA should able to deploy, upgrade airflow without issues
cherry-pick to valid release branches
> update oss chart to 1.11.0

- templates/logging-sidecar-configmap.yaml
- tests/chart_tests/test_logging_sidecar.py
- values.yaml
This PR adds supports to override default index prefix for sidecar logging. Allowing customisation for users to choose their own index prefix.
Note: This does not migrate existing index automatically users should take responsible to migrate their old index data to newer shifted ones.
https://github.com/astronomer/issues/issues/5947
QA should able to pass custom indexPrefix for sidecar logging
to all valid releases
> add sidecar logging index prefix overrides

- values.yaml
| imageName | oldTag | newTag |
|--------|--------|--------|
| ap-pgbouncer | 1.20.1 | 1.20.1-2 |
| ap-pgbouncer-exporter | 0.15.0-2 | 0.15.0-4 |
| ap-auth-sidecar | 1.25.2 | 1.25.2-2 | 
| ap-vector | 0.32.2 | 0.32.2-2|
https://github.com/astronomer/issues/issues/5870
https://github.com/astronomer/issues/issues/5988
QA should validate pgbouncer and exporter services should function as expected
cherry-pick to all valid releases
> update vendor packages to airflow chart

- .pre-commit-config.yaml
- Chart.lock
Add pre-commit hook that runs `helm dependency update` when Chart.yaml has changed.
N/A
No testing is needed. This is just a pre-commit change, and a lockfile change created by the new pre-commit hook. These changes don't alter anything that runs in customer environments. The only changes would be when we package the chart, and even that would be a no-op since the packaging scripts already run `helm dependency update`
> Add hook that runs 'helm dependency update' when Chart.yaml has changed.

- CODEOWNERS
Move the CODEOWNERS folks out of the file and into a GH org team.
N/A
N/A, this is just repo maintenance
Only the main branch is used for the CODEOWNERS feature. We might as well merge everywhere though.
> Move codeowners to an org team

- templates/dag-deploy/dag-server-auth-sidecar-configmap.yaml
- templates/dag-deploy/dag-server-service.yaml
- templates/dag-deploy/dag-server-statefulset.yaml
- templates/ingress.yaml
- tests/chart_tests/test_auth_sidecar.py
This PR adds support for authsidecar configuration in airflow chart in order to support external ingress controller
https://github.com/astronomer/issues/issues/6123
QA should able to access when external ingress controller is used
release-0.34
> initial authsidecar config for dag-server

- .circleci/config.yml
- .circleci/config.yml.j2
This adds parallel unit testing in CircleCI, which is something we do in astronomer/astronomer. The unittest step takes 18m20s on average as it is. <https://app.circleci.com/insights/github/astronomer/airflow-chart/workflows/install-airflow-chart/jobs?branch=master&reporting-window=last-90-days> This PR cuts that 18m20s down to about 4m20s <https://app.circleci.com/pipelines/github/astronomer/airflow-chart/2126/workflows/ff7ab1a7-3067-4a78-9ecf-e4ab7d7701d3/jobs/23388>
- https://github.com/astronomer/issues/issues/5199
No QA testing is needed. These changes are only CircleCI related.
> unittest in parallel

- Chart.yaml
update chart version 1.8.10
https://github.com/astronomer/issues/issues/6126
QA should able to install airflow chart without any issues
cherry-pick 1.8.10
> update chart version 1.8.10

- .pre-commit-config.yaml
- templates/dag-deploy/dag-deploy-rolebinding.yaml
- templates/generate-ssl.yaml
- tests/chart/test_dag_deploy_rolebinding.py
- Update pre-commit hooks
- Add a pygrep pre-commit hook that forbids the string `role-binding`
- `s/role-binding/rolebinding/g/`
https://github.com/astronomer/issues/issues/6362
Tests were modified. It's possible this will break stuff though, so we should look out for anywhere that complains about `role-binding`.
We should merge this everywhere if possible.
> Use 'rolebinding' and forbid 'role-binding'

- tests/k8s_schema/v1.30.0-standalone/configmap-v1.json
- tests/k8s_schema/v1.30.0-standalone/deployment-apps-v1.json
- tests/k8s_schema/v1.30.0-standalone/ingress-networking-v1.json
- tests/k8s_schema/v1.30.0-standalone/job-batch-v1.json
- tests/k8s_schema/v1.30.0-standalone/networkpolicy-networking-v1.json
- tests/k8s_schema/v1.30.0-standalone/role-rbac-v1.json
- tests/k8s_schema/v1.30.0-standalone/rolebinding-rbac-v1.json
- tests/k8s_schema/v1.30.0-standalone/secret-v1.json
- tests/k8s_schema/v1.30.0-standalone/service-v1.json
- tests/k8s_schema/v1.30.0-standalone/serviceaccount-v1.json
- tests/k8s_schema/v1.30.0-standalone/statefulset-apps-v1.json
- tests/k8s_schema/v1.30.0-standalone/storageclass-storage-v1.json
These cache files were missed when merging 1.30 support.
- https://github.com/astronomer/airflow-chart/pull/497
- https://github.com/astronomer/issues/issues/6319
No testing needed. These are just cache files that improve test resource utilization.
> Add k8s 1.30 schema files

- templates/dag-deploy/dag-server-statefulset.yaml
- tests/chart/test_dag_server_statefulset.py
- values.yaml
- Add `HOUSTON_SERVICE_ENDPOINT` env var
- Improve dag-server sts test cases
- https://github.com/astronomer/issues/issues/6374
- https://github.com/astronomer/issues/issues/5623
All of this code hasn't been in prod before and dag-deploy isn't going to work without it, so this can be tested during tests of dag-deploy rollback feature.
Merge only into whatever release-0.35 is going to use.
> 6233 dag rollback env

- templates/dag-deploy/dag-server-statefulset.yaml
- tests/chart/test_auth_sidecar.py
- values.yaml
This PR adds supports for dag server auth sidecar with securityContext support 
Note: for webserver and celery we pass securityContext from code reading from global astronomer authsidecar values, for dag-server authsidecar we have a slightly different approach to handle them with the chart itself
https://github.com/astronomer/issues/issues/6325
https://github.com/astronomer/issues/issues/6328
QA should see globally passed valid securityContext to dag server auth sidecar container
cherry-pick to release-1.10 and other upcomming releases
> add authsidecar security context support for dag server

- .pre-commit-config.yaml
- templates/_helpers.yaml
- templates/dag-deploy/dag-server-auth-sidecar-configmap.yaml
- templates/flower/flower-auth-sidecar-configmap.yaml
- templates/webserver/webserver-auth-sidecar-configmap.yaml
- tests/chart/test_auth_sidecar.py
- tests/chart/test_data/dag-server-authsidecar-nginx.conf
This PR enhances existing authsidecar config and fixes code duplication.
change 1: client_max_body_size initially nested inside auth block its now moved to server block to get applied for all location
change 2: server_tokens is added  every where in auth-sidecar nginx block  now its moved to common location and called every to reduce code duplication
change 3:  localhost in upstream block connects ipv6 by default and falls back to ipv4 this was causing error in first try and fallbacks to ipv4 and call passed sucessfully - we have changed to 127.0.0.1 to connect ipv4 by default
https://github.com/astronomer/issues/issues/6141
QA should validate webserver, flower and dag-server to see services comes up without any issues.
This also now enhances our upload limit for all auth proxy components …
> enhance nginx auth sidecar config

- tests/chart/test_auth_sidecar.py
- values.yaml
This PR has a minor imporvement over dag server auth sidecar. resource overrides support is already added for dag server authsidecar but key was missing in values.yaml this gives an initial impression of whether authsidecar supports resource overrides or not, this PR corrects the behaviour to show supported values in values.yaml
https://github.com/astronomer/issues/issues/6123
NA
cherry-pick to release-1.10 and upcomming releases
> add authsidecar resource section to default values

- values.yaml
- Use ap-dag-deploy 0.4.0 with rollbacks support
- astronomer/issues#6233
This can be tested with normal QA testing for the 0.35.0 release
Merge only into whatever version is going into astronomer/astronomer 0.35.0
> dag deploy 0.4.0

- templates/_helpers.yaml
- templates/dag-deploy/dag-server-auth-sidecar-configmap.yaml
- templates/flower/flower-auth-sidecar-configmap.yaml
- templates/webserver/webserver-auth-sidecar-configmap.yaml
- tests/chart/test_data/dag-server-authsidecar-nginx.conf
remove auth response headers from dag server auth sidecar nginx conf
https://github.com/astronomer/issues/issues/6383
QA should able to upload dags when auth-sidecar is enabled
cherry-pick to 1.11
> remove auth headers for dag server auth sidecar

- Makefile
- templates/dag-deploy/dag-deploy-networkpolicy.yaml
- tests/chart/test_dag_deploy_networkpolicy.py
- values.yaml
Add dag-deploy networkPolicy that prevents dag-deploy from being accessed from other namespaces except houston pod in astronomer namespace.
add support for BYO ingress with inbound auth sidecar 
- <https://github.com/astronomer/issues/issues/6479>
I manually tested this in an AWS cluster by confirming that when the policy was absent, dag-deploy server could be accessed from any namespace, and when this policy was in place, only the current namespace could access it, and also the houston pod in the astronomer deployed namespace.
This should be merged into releases >= 0.34
> Add dag-deploy networkPolicy

- templates/dag-deploy/dag-server-statefulset.yaml
- tests/chart/test_dag_server_statefulset.py
- values.yaml
Add persistentVolumeClaimRetentionPolicy support for dag server stateful to enable auto cleanup of pvc 
https://github.com/astronomer/issues/issues/6436
refer issue ticket
cherry-pick to release 1.10, 1.11
> add persistentVolumeClaimRetentionPolicy support in dag server

- templates/ingress.yaml
- tests/chart/test_ingress.py
update exposed route paths for dag server
PS: we already have a auth setup protecting these endpoints so we are safe here to expose them
https://github.com/astronomer/issues/issues/6518
QA should able to acess downloads and healthz endpoint 
> update exposed route paths for dag server

- values.yaml
dag-deploy version 0.5.1
- https://github.com/astronomer/issues/issues/6522
- https://github.com/astronomer/dag-deploy/pull/31
None needed. This value is actually passed in from houston, and we should consider removing this default. Maybe we can do that as part of https://github.com/astronomer/issues/issues/6481
Merge to 0.35, 0.36
> dag-deploy 0.5.1

- templates/flower/flower-auth-sidecar-configmap.yaml
- templates/webserver/webserver-auth-sidecar-configmap.yaml
update localhost upstream host to default ipv4 for authsidecar 
https://github.com/astronomer/issues/issues/6547
QA should not see any connection error stating ipv6 config
cherry-pick to release-1.10, release-1.11
> update localhost upstream host to default ipv4

- values.yaml
Image Name |  Old-tag|  New-tag 
-- | -- | -- 
ap-redis | 6.2.14 | 7.2.5
ap-pgbouncer | 1.21.0 | 1.23.1-1
ap-pgbouncer-exporter|  0.15.0-9 | 0.15.0-10
ap-git-daemon |3.18.7-1 | 3.18.8
ap-git-sync-relay | 0.0.3-4 |0.0.3-5
https://github.com/astronomer/issues/issues/6557
> Update ap-vendor packages 

- templates/logging-sidecar-configmap.yaml
This PR adds support for airflow downgrade pod logs to logging server from our sidecar based mechanism
https://github.com/astronomer/issues/issues/6401
QA should able to view logs in astro-ui 
> add airflow downgrade config to vector sidecar configuration list

- Chart.lock
- Chart.yaml
sync astronomer airflow chart to upstream oss chart 1.11.0 to bring new features 
fore more feature info check below link
https://airflow.apache.org/docs/helm-chart/stable/release_notes.html#airflow-helm-chart-1-11-0-2023-10-02
https://github.com/astronomer/issues/issues/6593
QA should validate all regular chart features
cherry-pick to 1.10 and 1.11
> update upstream airflow helm chart

- .circleci/config.yml
- bin/install-ci-tools
- metadata.yaml
- tests/k8s_schema/v1.31.0-standalone/configmap-v1.json
- tests/k8s_schema/v1.31.0-standalone/deployment-apps-v1.json
- tests/k8s_schema/v1.31.0-standalone/ingress-networking-v1.json
- tests/k8s_schema/v1.31.0-standalone/job-batch-v1.json
- tests/k8s_schema/v1.31.0-standalone/networkpolicy-networking-v1.json
- tests/k8s_schema/v1.31.0-standalone/role-rbac-v1.json
- tests/k8s_schema/v1.31.0-standalone/rolebinding-rbac-v1.json
- tests/k8s_schema/v1.31.0-standalone/secret-v1.json
- tests/k8s_schema/v1.31.0-standalone/service-v1.json
- tests/k8s_schema/v1.31.0-standalone/serviceaccount-v1.json
- tests/k8s_schema/v1.31.0-standalone/statefulset-apps-v1.json
- tests/k8s_schema/v1.31.0-standalone/storageclass-storage-v1.json
- Support k8s 1.31
- Bump patch versions of existing k8s versions
- Use helm 3.15.4
https://github.com/astronomer/issues/issues/6560
Normal testing is fine. QA can start testing k8s 1.31 clusters if they are not already.
> 6560 k8s 1 31

- tests/chart/test_airflow_scheduler.py
Add some Beyoncé Rule tests for the OSS airflow chart's scheduler.
https://github.com/astronomer/issues/issues/6628
No testing needed. These are just test additions to ensure that this behavior works as expected now and in the future.
> Add Beyoncé Rule tests for OSS airflow chart strategy

- tests/chart/test_pod_template.py
- values.yaml
currently our pod spec template is out of sync with oss airflow chart changes which seems quite outdated and lacks couple of component specific features , this PR brings back the features to our managed pod_template to keep up to date
**what changes are mapped here**
till now only global labels and pod annotations are respected with this new change will now repsect worker specific labels as well
https://github.com/astronomer/issues/issues/6650
https://github.com/astronomer/issues/issues/6593
https://github.com/astronomer/issues/issues/6594
cherry-pick to all valid airflow chart releases
> sync OSS chart 1.13.x pod template to astronomer airflow chart

- templates/_helpers.yaml
- templates/dag-deploy/dag-server-statefulset.yaml
- templates/flower/flower-auth-sidecar-configmap.yaml
- templates/webserver/webserver-auth-sidecar-configmap.yaml
- tests/chart/test_dag_server_statefulset.py
- tests/chart/test_data/dag-server-authsidecar-nginx.conf
- tests/chart/test_ingress.py
- values.yaml
This PR cherry-pick some of the major enhancements enabled in dag server service
* implements auth model for dag server service which requires auth sidecar enhancements ( removal of certain nginx headers from the nginx template)
* implements HOUSTON URL env in dag server statefulset to be used internally for connecting local endpoints
* CVE backports 
related https://github.com/astronomer/issues/issues/6459
related https://github.com/astronomer/issues/issues/6547
related https://github.com/astronomer/issues/issues/6383
related https://github.com/astronomer/issues/issues/6374
related https://github.com/astronomer/issues/issues/5623
related https://github.com/astronomer/issues/issues/6696
CVE fixes
related https://github.com/astronomer/issues/issues/6557
related …
> Add dag server improvements, update some other components

- templates/ingress.yaml
- tests/chart/test_ingress.py
remove auth sidecar tls secret name hard coding and sync with global tls secretname, this allows users to pass their own secret name that will synced across all deployments.
https://github.com/astronomer/issues/issues/6344
QA should able to pass custom tls secret name for authsidecar and regular deployment from astronomer global values
cherry-pick to 1.11 and 1.13
> remove authsidecar tls secret hard codings

- Chart.lock
- Chart.yaml
- tests/chart/test_airflow.py
This PR points back to custom fork version from 1.13.1 of oss chart to add support to pass custom env vars to migrate database job 
- https://github.com/astronomer/issues/issues/6646
- related oss PR https://github.com/apache/airflow/pull/42345
NA
cherry-pick to 1.13
> update astronome airflow chart with custom forked airflow chart

- tests/chart/test_pod_template.py
- values.yaml
This change allows workers specific env to be auto include to pod template when specified
our current shipped podMutation templates lacks few features from oss helm chart , this PR addresses the behaviour by including the required changes to work with astronomer airflow chart 
- changes included PR adds a fix where workers specific env to be auto included to pod mutation template which allows the airflow task pod to use the worker env vars
- https://github.com/astronomer/issues/issues/6650
- https://github.com/astronomer/issues/issues/6593
- https://github.com/astronomer/issues/issues/6594
QA should see worker specific env are viewed in the airflow task pods 
cherry-pick to release-1.13
> sync astronomer airflow chart with oss chart

- values.yaml
Bump pgbouncer-exporter to 0.18.0 which is compatible with pgbouncer 1.23 metrics. https://github.com/Vonng/pg_exporter/commit/8e24e9b307f9ed7c7489f4489947e5e733e09c0c
https://github.com/astronomer/issues/issues/6761
Make sure pgbouncer metrix work in 0.36.0
This should go anywhere that we are using pgbouncer 1.23
> pgbouncer-exporter 0.18.0

- templates/_helpers.yaml
- templates/dag-deploy/dag-server-statefulset.yaml
- templates/git-sync-relay/git-sync-relay-deployment.yaml
While working on https://github.com/astronomer/issues/issues/6789 I found a typo, so here is that fix and some whitespace changes that we can backport to all branches where git-sync sidecar is used.
- Fix a typo.
- Whitespace changes.
Not really related to https://github.com/astronomer/issues/issues/6789 but this was found while working on it.
CI tests are sufficient.
Backport to anywhere we use git-sync-relay.
> Whitespace and typo fix

- templates/_helpers.yaml
- templates/dag-deploy/dag-server-statefulset.yaml
- tests/chart/test_dag_server_statefulset.py
- values.yaml
add liveliness and readiness support for dag server
- https://github.com/astronomer/issues/issues/6876
Update on validation
Yet to update
> add liveliness and readiness support for dag server

- templates/git-sync-relay/git-sync-relay-deployment.yaml
- tests/chart/test_git_sync_relay_deployment.py
- values.yaml
This PR adds support for git sync deployment containers with probes support and introduces new granular field segments for per container config support
- <https://github.com/astronomer/issues/issues/6876>
- <https://github.com/astronomer/issues/issues/6746>
- https://github.com/astronomer/issues/issues/6874
QA should able to override the resource and probe values from astronomer helm chart 
cherry-pick to release-1.13
> gitsync relay probes support

- tests/chart/test_pod_template.py
- values.yaml
Add resource spec support for pod template to make kubernetes executor to have configurable resources
- https://github.com/astronomer/issues/issues/6926
QA should able to overrides task pod resources with kubernetes executor from the UI or api
release-1.13
> add workers resource spec to pod template

- .gitignore
- Makefile
- docs/git-clone.d2
- templates/git-sync-relay/git-sync-relay-deployment.yaml
- templates/git-sync-relay/git-sync-relay-pvc.yaml
- tests/__init__.py
- tests/chart/helm_template_generator.py
- tests/chart/test_git_sync_relay_deployment.py
- tests/k8s_schema/v1.27.0-standalone/persistentvolumeclaim-v1.json
- tests/k8s_schema/v1.28.0-standalone/persistentvolumeclaim-v1.json
- tests/k8s_schema/v1.29.0-standalone/persistentvolumeclaim-v1.json
- tests/k8s_schema/v1.30.0-standalone/persistentvolumeclaim-v1.json
- tests/k8s_schema/v1.31.0-standalone/persistentvolumeclaim-v1.json
- values.yaml
Add git-sync volume mode.
- <https://github.com/astronomer/issues/issues/6789>
I've tested this manually. We'll need more comprehensive testing from QA since this is a new feature that will have astro-ui and houston components.
This is only meant for 0.37
> 6789 git-sync volume support

- templates/_helpers.yaml
- templates/git-sync-relay/git-sync-relay-deployment.yaml
- templates/git-sync-relay/git-sync-relay-serviceaccount.yaml
- tests/chart/test_git_sync_relay_serviceaccount.py
- values.yaml
Add support for service account to  git sync relay component to ensure or skip policy managers rejecting the deploy request
https://github.com/astronomer/issues/issues/6747
Yet to update
cherry-pick to master
> add git sync relay service account support

- values.yaml
This PR Updates  ap-vendor packages to resolve some of the CVE's for astronomer software 
Image Name |  old  Tag| New tag |
-- | -- | -- |
ap-vector | 0.42.0 | 0.44.0-1
git-daemon  | 3.18.9 | 3.20.3-1
git-sync-relay | 0.0.3-6 |0.0.3-7
git-sync | 3.6.9 | 4.2.3-1
https://github.com/astronomer/issues/issues/6830
QA should be able to test git sync and logging-sidecar features without any fail 
cherry-picked into release-037 and release-036
> upgrading ap-vendor packages

- templates/git-sync-relay/git-sync-relay-pvc.yaml
- tests/chart/test_git_sync_relay_pvc.py
Correct the git-sync-relay shared_volume mode and add pvc tests.
- <https://github.com/astronomer/issues/issues/6965>
I added unit tests, but have not tested in an actual cluster. @himabindu07 will do so to circle back on <https://github.com/astronomer/issues/issues/6965> which she opened.
Merge only to release-1.13 branch.
> Fix PVC mode for git-sync-relay shared_volume

- values.yaml
Use quay.io/astronomer/ap-git-sync-relay:0.1.8 with added debugging.
https://github.com/astronomer/issues/issues/7004
This is just additional debugging code that is not enabled unless the environment has "DEBUG=1" set. No testing is needed.
Merge only to release-1.13
> quay.io/astronomer/ap-git-sync-relay:0.1.8 with added debugging

- templates/git-sync-relay/git-sync-relay-networkpolicy.yaml
- tests/chart/test_git_sync_relay_networkpolicy.py
This PR fixes an issue where calico or any network plugin is being installed on a secure kubernetes cluster git based deployment with poll or webhook over git_daemon mode will fail to sync the code changes. 
- https://github.com/astronomer/issues/issues/7028
QA should able to deploy git sync based deployments with webhook or poll when git_daemon mode is selected
cherry-pick to release-1.14 and master
> expose network policy for git sync relay intercommunication

- values.yaml
ap-git-sync-relay which has some tiny improvements like re-ordering some code for slightly better flow, and not warning about an operation that is normal.
- <https://github.com/astronomer/issues/issues/6786>
- <https://github.com/astronomer/git-sync-relay/pull/6>
I have manually tested this code for astronomer/astronomer 0.37.0. No QA is needed for that release.
Merge to 1.14, should also work with 1.13.
> ap-git-sync-relay 0.1.9 which has tiny improvements.

- templates/airflow-scc-anyuid.yaml
add scc support for gitsync relay service
- https://github.com/astronomer/issues/issues/7073
QA should be able to create deployment and see no issues with git sync based deployments
cherry-pick to release-1.14
> add scc support for gitsync relay service

- templates/_helpers.yaml
- tests/chart/test_pgbouncer.py
fix pgbouncer service account name
pgbouncer service account template has been changed in oss chart since the upgrade of 1.13 and we have ported all airflow related service account changes inside the chart
- https://github.com/astronomer/issues/issues/7096
- https://github.com/astronomer/issues/issues/7096
QA should now see refactored service account in the pgbouncer deployment spec
cherry-pick to release-1.13,1.14,master
> fix pgbouncer service account name

- values.yaml
> [!TIP]
> This is a regular image update activity
| imageName | oldTag | newTag |
|--------|--------|--------|
| ap-statsd-exporter | 0.27.2 | 0.28.0-2 | 
| ap-pgbouncer | 1.23.1-1 | 1.24.0-1 | 
| ap-pgbouncer-exporter | 0.18.0 | 0.18.0-3 |
| ap-git-sync | 4.2.3-1 | 4.2.3-3 | 
| ap-auth-sidecar | 1.27.1 | 1.27.4-1 |
| ap-vector | 0.44.0-1 | 0.45.0-1 |
| ap-dag-deploy | 0.5.0 | 0.6.5 |
| ap-git-daemon | 3.20.5 | 3.21.3-1 |
- https://github.com/astronomer/issues/issues/7106
QA general testing
cherry-pick to release-1.14
> update airflow vendor images

- tests/chart/helm_template_generator.py
- tests/k8s_schema/v1.32.0-standalone/cronjob-batch-v1.json
- tests/k8s_schema/v1.32.0-standalone/ingress-networking-v1.json
- tests/k8s_schema/v1.32.0-standalone/networkpolicy-networking-v1.json
- tests/k8s_schema/v1.32.0-standalone/persistentvolumeclaim-v1.json
- tests/k8s_schema/v1.32.0-standalone/storageclass-storage-v1.json
Update the raw.githubusercontent.com URL for accessing assets from within the GH repo used by the k8s schema file validator.
Also add `parents=True` to `Path.mkdir()` when caching k8s schema files.
This also deletes and re-adds all schema files to ensure that we have only what is needed, and we have the latest files.
- <https://github.com/astronomer/issues/issues/7102>
- <https://github.com/astronomer/astronomer/pull/2548>: Equivalent PR in astronomer
I've manually tested this by deleting all the schema files and observed them being recreated and producing no diff.
Merge everywhere since this is a change in a third party resource that needs to be updated.
> Update BASE_URL_SPEC, mkdir(parents=True)

- templates/_helpers.yaml
- templates/airflow-scc-anyuid.yaml
- tests/chart/test_dag_processor.py
- tests/chart/test_scc.py
- tests/k8s_schema/v1.29.0-standalone/securitycontextconstraints-security-v1.json
- tests/k8s_schema/v1.30.0-standalone/securitycontextconstraints-security-v1.json
- tests/k8s_schema/v1.31.0-standalone/securitycontextconstraints-security-v1.json
- tests/k8s_schema/v1.32.0-standalone/securitycontextconstraints-security-v1.json
Add dag processor scc support for openshift aro and on prem clusters
https://github.com/astronomer/issues/issues/6572
QA should able to provision standalone dag processor with sccEnabled feature
cherry-pick to all valid branches
> add base scc feature json schema and dag processor testing

- templates/dag-deploy/dag-deploy-networkpolicy.yaml
- templates/git-sync-relay/git-sync-relay-networkpolicy.yaml
- tests/chart/test_dag_deploy_networkpolicy.py
- tests/chart/test_git_sync_relay_networkpolicy.py
- values.yaml
Adds network policy support for astronomer provisioned airflow components 
fixes  https://github.com/astronomer/issues/issues/7205
QA should verify
```
airflow:
networkPolicies:
enabled: false
```
Yet to update
> enable networkpolicy support for airflow astronomer components

- templates/dag-deploy/dag-server-statefulset.yaml
- templates/git-sync-relay/git-sync-relay-deployment.yaml
- tests/chart/conftest.py
- tests/chart/test_dag_server_statefulset.py
- tests/chart/test_git_sync_relay_deployment.py
- values.yaml
add taint,tolleration and node selector support for git-sync-relay and dag-server
- https://github.com/astronomer/issues/issues/7526
- https://github.com/astronomer/issues/issues/7335
QA should able to override taint,tolleration and node selector for git-sync and dag-server components
merge to master and release-1.15
> add taint, toleration and node selector support

- templates/dag-deploy/dag-server-statefulset.yaml
- templates/git-sync-relay/git-sync-relay-deployment.yaml
- tests/chart/test_dag_server_statefulset.py
- tests/chart/test_git_sync_relay_deployment.py
- values.yaml
add taint,tolleration and node selector support for git-sync-relay and dag-server
- https://github.com/astronomer/issues/issues/7526
- https://github.com/astronomer/issues/issues/7335
QA should able to override taint,tolleration and node selector for git-sync and dag-server components
merge to master and release-1.15
> \/airflow wide config pattern enablement for node selector, tolleration and taints

- tests/chart/test_pod_template.py
- values.yaml
currently airflow toleration, nodeselector and affinity takes higher precedence than worker specific configuration which is incorrect with this new change worker configuration takes higher priority than airflow defaults
- https://github.com/astronomer/issues/issues/7615
QA should able to pass customer nodeSelector, tolerations and affinity config to workers section to see those values are getting higher precedence order than defaults
merge to master, release-1.15
> fix workers scheduling ordering

- values.yaml
Add airflow  execution api server url configuration which is needed for airflow3 
https://github.com/astronomer/issues/issues/7650
QA should able to run tasks from airflow3
merge to master and release-1.0
> add execution api server url

- templates/dag-deploy/dag-server-statefulset.yaml
- tests/chart/test_dag_server_statefulset.py
Generate Houston service URL from api that will be passed to airflow deployment to update deploy revision to database .
previously it was all way around connecting to local houston url , due to our new control and dataplane logic it will need a public URL for internal communication
- https://github.com/astronomer/issues/issues/7656
merge to master
> remove houston service endpoint from dagserver

- templates/logging-sidecar-configmap.yaml
- tests/chart/test_logging_sidecar.py
This change adds support for collecting logs from the api-server component in the Vector logging sidecar configuration. The api-server component was missing from the existing component filters, preventing its logs from being properly collected and forwarded to Elasticsearch.
- Added `filter_apiserver_logs` transform to filter logs specifically from the `api-server` component
- Updated `transform_remove_fields` inputs to include the new `api-server` filter
- https://github.com/astronomer/issues/issues/7390
API server logs will now be collected alongside other Airflow component logs and indexed in Elasticsearch with the same naming pattern as existing components when usinf Airflow3
Master, 1.17
> Addapiserver

- Chart.yaml
- templates/webserver/webserver-auth-sidecar-configmap.yaml
- tests/chart/test_auth_sidecar.py
remove webserver authsidecar config when airflow3 is enabled
- https://github.com/astronomer/issues/issues/7955
QA should not see webserver authsidecar configmap when airflow 3 enabled
merge to master and release-1.0
> remove webserver authsidecar config when airflow3 is enabled
